Repository umbraco/UmbracoDocs, pull requests merged in 2019-07, with the labels that each got.

#1727 V7 to 8 migration
  Getting-Started/Setup/Upgrading/7-8-migration-dataTypes.md
  Getting-Started/Setup/Upgrading/images/content-on-8.1.png
  Getting-Started/Setup/Upgrading/images/fresh-8.1-site.png
  Getting-Started/Setup/Upgrading/images/set-umbraco-version.png
  Getting-Started/Setup/Upgrading/images/upgrade-to-8.1.png
  Getting-Started/Setup/Upgrading/images/upgrading-7.14.png
  Getting-Started/Setup/Upgrading/images/v7-content.png
  Getting-Started/Setup/Upgrading/migrating-to-v8.md
  Getting-Started/Setup/Upgrading/version-specific.md
  v8documentation.md
Labels: category/pending-release

#1751 Add documentation about UmbracoMapper
  Reference/Mapping/index-vpre8.1.md
  Reference/Mapping/index.md
Labels: category/pending-release

#1760 V8.1/update/specific update instructions
  Getting-Started/Setup/Upgrading/version-specific.md
Labels: category/pending-release

#1725 Temp 1627 additional test examples
  Implementation/Unit-Testing/index.md
Labels: status/awaiting-feedback

#1641 Email clash when adding cloud user
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Labels: category/umbraco-cloud
