Repository umbraco/UmbracoDocs, pull requests merged in 2020-10, with the labels that each got.

#2737 Fixing broken link
  Umbraco-Cloud/Troubleshooting/troubleshooting-portal.md
Labels: hacktoberfest/contrib-2020

#2739 updated doc
  Extending/Dashboards/index.md
  Implementation/Composing/index.md
  Implementation/Data-Persistence/index.md
Labels: hacktoberfest/contrib-2020

#2740 Fix link in faqs section to point to the correct one
  Umbraco-Cloud/Frequently-Asked-Questions/index.md
Labels: hacktoberfest/contrib-2020

#2745 changed the default mb mode
  Reference/Templating/Modelsbuilder/configuration.md
Labels: hacktoberfest/contrib-2020

#2742 Update Build-a-Block-Editor.md
  Extending/Property-Editors/Build-a-Block-Editor.md
Labels: hacktoberfest/contrib-2020

#2744 Added notes to troubleshoot some issues with OpenGraph implementation
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4-v7.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4.md
Labels: category/umbraco-heartcore, hacktoberfest/contrib-2020

#2749 Deploying deletes
  Umbraco-Cloud/Deployment/Deploying-Deletions/index.md
Labels: category/umbraco-cloud, hacktoberfest/contrib-2020

#2741 Added documentation for the umbLayoutSelector selector
  Reference/Angular/Directives/index.md
  Reference/Angular/Directives/umbLayoutSelector/Index.md
  Reference/Angular/Directives/umbLayoutSelector/images/umbLayoutSelector.png
  Reference/Angular/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2748 Warning message to use Umbraco.Web.Models
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Related-Links2.md
Labels: category/umbraco-cms

#2743 Custom error pages in umbraco
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2752 Add links and iframes to Uno articles
  Umbraco-Uno/Creating-Content/Customize-Your-Theme/index.md
  Umbraco-Uno/Creating-Content/Work-with-content/index.md
  Umbraco-Uno/Manage-users/Users/index.md
Labels: hacktoberfest/contrib-2020

#2751 Updated with info about the order
  Umbraco-Cloud/Set-Up/Manage-Environments/index.md
Labels: category/umbraco-cloud, hacktoberfest/contrib-2020

#2754 Fixes typos: supress/suppresing to suppress/suppressing
  Add-ons/UmbracoCourier/Developer/index.md
  Contribute/Code-samples/index.md
  Contribute/Style-Guide/index.md
  Reference/UmbracoVolatile.md
Labels: hacktoberfest/contrib-2020

#2762 Added info for EmailAddress DataType
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/images/EmailAddress-DataType-Content.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/images/EmailAddress-DataType-v8.8.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/images/EmailAddress-DataType-v8.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/images/mandatory-checkbox.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/umbraco-cms

#2768 Removing obsolete extension
  Reference/Searching/Examine/Quick-Start/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2767 Small grammar changed to the Umbraco Forms.
  Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
Labels: category/umbraco-forms, hacktoberfest/contrib-2020

#2771 Update index-v7.md
  Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items/index-v7.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2772 Removed deploy settings from troubleshooting
  Umbraco-Cloud/Deployment/Deploy-Settings/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/Deploy-Settings/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/index.md
Labels: category/broken-link, category/umbraco-cloud, hacktoberfest/contrib-2020

#2775 Update index.md
  Tutorials/Creating-a-Property-Editor/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2753 Update migrating-to-v8.md
  Getting-Started/Setup/Upgrading/migrating-to-v8.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2778 List view documentation
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/Bulk-action.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/Content-app-icon.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/enable-listview.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/list-icon.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/list-member-picked.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-content-example-email-settings.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-content-example-email.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-property-dropdown.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-property.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-settings-2.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview-settings.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/listview.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/member-picker-settings.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/member-picker.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/others-result.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/others.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/picked-member.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2781 Update the Block List documentation to show how to add an angularJS controller
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2780 Add tutorial on creating and distributing a package
  Tutorials/Creating-and-distributing-a-package/images/U_Package_team.png
  Tutorials/Creating-and-distributing-a-package/images/class-library.png
  Tutorials/Creating-and-distributing-a-package/images/dashboard.png
  Tutorials/Creating-and-distributing-a-package/images/gh-secret.png
  Tutorials/Creating-and-distributing-a-package/images/github-repo.png
  Tutorials/Creating-and-distributing-a-package/images/gulp-watch.png
  Tutorials/Creating-and-distributing-a-package/images/our-package-data.png
  Tutorials/Creating-and-distributing-a-package/images/package-files.png
  Tutorials/Creating-and-distributing-a-package/images/package-info.png
  Tutorials/Creating-and-distributing-a-package/images/package-overview.png
  Tutorials/Creating-and-distributing-a-package/images/packagexml.png
  Tutorials/Creating-and-distributing-a-package/images/zip-files.png
  Tutorials/Creating-and-distributing-a-package/index.md
Labels: hacktoberfest/contrib-2020

#2799 Add GraphQL docs link to Heartcore index page
  Umbraco-Heartcore/index.md
Labels: category/umbraco-heartcore, hacktoberfest/contrib-2020

#2782 Added documentation for the changeTitle
  Reference/Angular/Directives/changeTitle/Index.md
  Reference/Angular/Directives/changeTitle/images/defaultview.png
  Reference/Angular/Directives/changeTitle/images/editblog.png
  Reference/Angular/Directives/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2800 Add decimal property editor
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/images/content-example.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/images/definition-example.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2807 fixed typo 'can can'
  Reference/Events/EditorModel-Events/index.md
Labels: hacktoberfest/contrib-2020

#2788 Adds documentation for new external login provider functionality and cleans up a bit of the existing docs
  Reference/Security/Security-settings/index.md
  Reference/Security/auto-linking-v7.3.0.md
  Reference/Security/auto-linking.md
  Reference/Security/backoffice-user-manager-v7.3.0.md
  Reference/Security/backoffice-user-manager.md
  Reference/Security/external-login-providers.md
  Reference/Security/index-v7.md
  Reference/Security/index.md
Labels: category/pending-release, category/umbraco-cms

#2816 Upate emailaddress datatype
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/images/EmailAddress-DataType-v88.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2814 Add video link to net MVC sample
  Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md
Labels: category/umbraco-heartcore, hacktoberfest/contrib-2020

#2820 Add Member Group Picker
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/images/Member-Group-Picker-Content.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/images/Member-Picker-DataType.png
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2832 Update Checbox
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2020

#2836 Heartcore GraphQL filtering, ordering and paging
  Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
  Umbraco-Heartcore/API-Documentation/GraphQL/index.md
  Umbraco-Heartcore/index.md
Labels: category/umbraco-heartcore

#2817 Add GraphQL schema generation docs for filters and orderby
  Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
  Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/index.md
  Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
  Umbraco-Heartcore/API-Documentation/GraphQL/index.md
  Umbraco-Heartcore/index.md
Labels: category/pending-release, category/umbraco-heartcore
