Repository umbraco/UmbracoDocs, pull requests merged in 2020-11, with the labels that each got.

#2835 fixed badge for compact-log-viewer
  Getting-Started/Backoffice/LogViewer/badge/English_get.png
  Getting-Started/Backoffice/LogViewer/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2020

#2837 Update Content Picker
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Content-Picker/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2020

#2839 Change meta Umbraco v of the permissions
  Getting-Started/Setup/Server-Setup/permissions.md
Labels: category/umbraco-cms

#2843 Fixed typos and changed some sentence structure.
  Umbraco-Heartcore/Getting-Started-Cloud/index.md
Labels: category/umbraco-heartcore

#2840 minor correction and typo fixes
  Umbraco-Heartcore/index.md
Labels: category/umbraco-heartcore

#2846 Read desc for more details.
  Umbraco-Heartcore/Getting-Started-Cloud/Deployment-workflow/index.md
Labels: category/umbraco-heartcore

#2844 Read desc for details.
  Umbraco-Heartcore/Getting-Started-Cloud/The-Cloud-Portal/index.md
Labels: category/umbraco-heartcore

#2845 Read desc for details.
  Umbraco-Heartcore/Getting-Started-Cloud/Environments/index.md
Labels: category/umbraco-heartcore

#2847 Update Label Property Editor
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Label.md
Labels: category/umbraco-cms

#2841 Updating instructions for TinyMCE Code Sample
  Reference/Config/tinyMceConfig/index.md
Labels: category/umbraco-cms

#2830 Move changeTitle documentation
  Reference/Angular/Directives/index.md
  Reference/Angular/Services/eventsService/changeTitle/Index.md
  Reference/Angular/Services/eventsService/changeTitle/images/defaultview.png
  Reference/Angular/Services/eventsService/changeTitle/images/editblog.png
  Reference/Angular/Services/eventsService/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2020

#2842 Fixed a few typos and changed the sentence structure.
  Umbraco-Heartcore/Getting-Started-Cloud/Creating-a-Heartcore-project/index.md
Labels: category/umbraco-heartcore

#2833 Added prerequisites + Latch renewal period
  Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md
Labels: category/umbraco-cloud, hacktoberfest-accepted

#2838 Added a section about the env error log
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md
Labels: category/umbraco-cloud, hacktoberfest/contrib-2020

#2851 Fix deeplink
  Getting-Started/Setup/Server-Setup/azure-web-apps-v7.md
Labels: category/broken-link, category/umbraco-cms

#2823 Add value to checkbox property editor
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2020

#2854 Update Multinode treepicker property editor
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index.md
Labels: category/umbraco-cms

#2855 Update index.md
  Umbraco-Uno/Working-with-Forms/Recaptcha/index.md
Labels: category/umbraco-uno

#2777 Extending Uno
  Umbraco-Uno/Creating-Content/Extending-Uno/images/embedded-calendly-service.png
  Umbraco-Uno/Creating-Content/Extending-Uno/index.md
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2020

#2864 Update index.md
  Extending/Content-Apps/index.md
Labels: category/umbraco-cms

#2863 Update wrong Editor Alias for Umbraco.Integer
  Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/index.md
Labels: category/umbraco-heartcore

#2862 Add more examples of how to extract block list content data
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
Labels: category/umbraco-cms

#2813 Added detail to how different "Lifetimes" work
  Implementation/Services/index.md
  Reference/Using-Ioc/index.md
Labels: hacktoberfest-accepted

#2861 Added how to make use of fileupload predefined file types
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/FileUpload/images/fileupload.png
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/FileUpload/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/index.md
Labels: category/umbraco-forms

#2879 Add preview argument to Heartcore GraphQL schema generation
  Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
Labels: category/umbraco-heartcore

#2877 Umbraco Uno - Creating an area for Members
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/images/example-of-logout-button.png
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/images/example-of-public-access-config.png
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/images/login-widget-example.png
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/images/register-widget-example.png
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/images/unicorn-club-restricted-area.png
  Umbraco-Uno/Creating-Content/Creating-an-area-for-Members/index.md
  Umbraco-Uno/Manage-users/index.md
Labels: category/umbraco-uno

#2882 Media updates on cloud
  Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/index.md
  Umbraco-Cloud/Set-Up/Media/index.md
Labels: category/umbraco-cloud

#2848 New User deploy permissions
  Umbraco-Cloud/Set-Up/Users-On-Cloud/images/Granular.png
  Umbraco-Cloud/Set-Up/Users-On-Cloud/images/Granular_node.png
  Umbraco-Cloud/Set-Up/Users-On-Cloud/images/Granular_permission.png
  Umbraco-Cloud/Set-Up/Users-On-Cloud/images/Users.png
  Umbraco-Cloud/Set-Up/Users-On-Cloud/images/default_permisions.png
  Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
Labels: category/umbraco-cloud

#2253 Update IPublishedContent properties docs to reflect coming obsolete methods
  Reference/Querying/IPublishedContent/Properties/index.md
Labels: category/pending-release, category/umbraco-netcore

#2887 Adds wording for showing draft content with GraphQL
  Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
Labels: category/umbraco-heartcore

#2790 Add info on property replacement
  Extending/Packages/UmbPack/index.md
Labels: category/pending-release, hacktoberfest-accepted

#2894 Add trailing slash rewrite rule to the "Rewrites on Cloud" article
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
  Umbraco-Cloud/Set-Up/Media/index.md
Labels: category/umbraco-cloud

#2898 Changing trailing slash redirect to a better approach
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
Labels: category/umbraco-cloud

#2899 Adds using statement and updates description of using RenderUmbracoFor…
  Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
Labels: category/umbraco-forms

#2900 Update BLockListEditor
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
Labels: category/umbraco-cms

#2895 Update Textbox
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox/index.md
Labels: category/umbraco-cms

#2901 Update to reflect how to move from manual cert. to Latch
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Security-Certificates/index.md
Labels: category/umbraco-cloud

#2878 Code samples for adding values to properties programmatically
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Numeric/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textarea/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
Labels: category/code-example, category/umbraco-cms

#2905 Properly closing comment in tinymce table config example
  Reference/Config/tinyMceConfig/index.md
Labels: category/umbraco-cms

#2904 Update Repeatable textstrings
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multiple-Textbox/index.md
Labels: category/umbraco-cms

#2866 Added sample on how to create nested content programmatically
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Labels: category/code-example, category/umbraco-cms

#2912 Added basic troubleshooting tips for custom error pages tutorial
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms
