Repository umbraco/UmbracoDocs, pull requests merged in 2020-05, with the labels that each got.

#2404 Add info about aborting /umbraco requests in load balanced environments
  Reference/Security/Security-hardening/index.md
Labels: category/umbraco-cms

#2428 Feature docs/back office search
  Extending/Backoffice-Search/index.md
  Extending/index.md
Labels: category/umbraco-cms

#2478 Adds in example of using TourFilters to disable certain tours
  Extending/Backoffice-Tours/index.md
Labels: category/umbraco-cms

#2472 Grid for The Starter kit
  Umbraco-StarterKit/Widgets/Grid/Accordion/index.md
  Umbraco-StarterKit/Widgets/Grid/Button/images/Button-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Button/images/Button-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Button/images/Button-Options-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Button/index.md
  Umbraco-StarterKit/Widgets/Grid/Card/index.md
  Umbraco-StarterKit/Widgets/Grid/Code/index.md
  Umbraco-StarterKit/Widgets/Grid/Header/images/Header-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Header/images/Header-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Header/index.md
  Umbraco-StarterKit/Widgets/Grid/Images/Grid-Settings.png
  Umbraco-StarterKit/Widgets/Grid/Images/index.md
  Umbraco-StarterKit/Widgets/Grid/Line-break/images/Line-Breaker-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Line-break/images/Line-Breaker-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Line-break/index.md
  Umbraco-StarterKit/Widgets/Grid/Navigation/index.md
  Umbraco-StarterKit/Widgets/Grid/Pod/index.md
  Umbraco-StarterKit/Widgets/Grid/Price-list/images/Price-List-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Price-list/images/Price-List-frontend2.png
  Umbraco-StarterKit/Widgets/Grid/Price-list/images/Price-List.png
  Umbraco-StarterKit/Widgets/Grid/Price-list/index.md
  Umbraco-StarterKit/Widgets/Grid/Price-table/images/Price-Table-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Price-table/images/Price-Table-backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Price-table/images/Price-Table-frontend1.png
  Umbraco-StarterKit/Widgets/Grid/Price-table/images/Price-Table-frontend2.png
  Umbraco-StarterKit/Widgets/Grid/Price-table/index.md
  Umbraco-StarterKit/Widgets/Grid/Quote/images/Quote-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Quote/images/Quote-frontend1.png
  Umbraco-StarterKit/Widgets/Grid/Quote/index.md
  Umbraco-StarterKit/Widgets/Grid/Slider/index.md
  Umbraco-StarterKit/Widgets/Grid/Sub-grid/index.md
  Umbraco-StarterKit/Widgets/Grid/Text/images/Text-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Text/images/Text-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Text/index.md
  Umbraco-StarterKit/Widgets/Grid/Umbraco-Form/images/Umbraco-Form-backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Umbraco-Form/images/Umbraco-Forms-frontend.png
  Umbraco-StarterKit/Widgets/Grid/Umbraco-Form/index.md
  Umbraco-StarterKit/Widgets/Grid/Video/images/Video-Backoffice.png
  Umbraco-StarterKit/Widgets/Grid/Video/images/Video-Frontend.png
  Umbraco-StarterKit/Widgets/Grid/Video/index.md
  Umbraco-StarterKit/Widgets/Grid/index.md
Labels: category/umbraco-starterkit

#2305 Added new page about declaring property editors
  Extending/Property-Editors/Declaring-your-property-editor.md
Labels: state/needs-investigation

#2493 Added a new page for language mismatch error troubleshooting
  Umbraco-Cloud/Troubleshooting/Deployments/Language-Mismatch/images/detailed-error.png
  Umbraco-Cloud/Troubleshooting/Deployments/Language-Mismatch/images/error.png
  Umbraco-Cloud/Troubleshooting/Deployments/Language-Mismatch/images/kudutools.png
  Umbraco-Cloud/Troubleshooting/Deployments/Language-Mismatch/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/index.md
Labels: category/umbraco-cloud

#2497 Portal backoffice frontend
  Umbraco-StarterKit/Getting-Started/index.md
Labels: category/umbraco-starterkit
