Repository umbraco/UmbracoDocs, pull requests merged in 2021-07, with the labels that each got.

#3308 Remove Task and TaskType
  Reference/Management/Models/Task.md
  Reference/Management/Models/TaskType.md
  Reference/Management/Models/index.md
Labels: category/missing-documentation

#3302 Update Extending-UmbracoApplication.md
  Reference/Events/Extending-UmbracoApplication.md
Labels: category/code-example

#3293 Added v9 docs for load balancing.
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v9.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication-v9.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/files-replicated.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/files-shared.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced-v9.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/flexible.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/index-v9.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/logging.md
  Fundamentals/Setup/Upgrading/general-v9.md
Labels: category/umbraco-v9

#3265 Routing custom controllers v9
  Reference/Routing/custom-controllers-v9.md
  Reference/Routing/custom-controllers.md
Labels: category/umbraco-v9

#3281 Updated permissions to match v9 + fixes index files
  Fundamentals/Setup/Server-Setup/index-v9.md
  Fundamentals/Setup/Server-Setup/permissions-v9.md
  Fundamentals/Setup/index-v9.md
Labels: category/umbraco-v9

#3325 Prepare v9 main docs for rc1
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-v9

#3243 Updated property editors for V9
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/CheckBox-List/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Content-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Date-Time/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Eye-Dropper-Color-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Add-Value-Programmatically-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Render-Grid-In-Template.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Label-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Markdown-Editor/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multiple-Textbox/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Numeric/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Rich-Text-Editor/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Slider/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Textarea/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index-v9.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/User-Picker/index-v9.md
  Fundamentals/Backoffice/Property-Editors/images/Media-picker-dataType-v9.png
  Fundamentals/Backoffice/Property-Editors/index-v9.md
Labels: category/umbraco-v9

#3330 Fix to custom health check code
  Extending/Health-Check/index.md
Labels: category/code-example

#3317 Added a list of the IPs we fire webhooks from
  Umbraco-Heartcore/Getting-Started-Cloud/Webhooks/index.md
Labels: category/umbraco-heartcore

#3336 Cleared up some confusion around this feature.
  Umbraco-Heartcore/API-Documentation/index.md
Labels: category/umbraco-heartcore

#3341 Added a mention to the tours configuration setting
  Extending/Backoffice-Tours/index.md
Labels: category/umbraco-cms

#3351 Reference management models media type v9
  Reference/Management/Models/MediaType-v9.md
Labels: category/umbraco-v9

#3344 Reference management models language v9
  Reference/Management/Models/Language-v9.md
Labels: category/umbraco-v9

#3342 Reference management models dictionary item
  Reference/Management/Models/DictionaryItem-v9.md
Labels: category/umbraco-v9

#3340 Reference management models content type v9
  Reference/Management/Models/ContentType-v9.md
Labels: category/umbraco-v9

#3332 Reference management models data type v9
  Reference/Management/Models/DataType-v9.md
Labels: category/umbraco-v9

#3345 Added documentation on the Deploy configuration option ignoreBrokenDependencies
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v9.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Labels: category/umbraco-deploy

#3261 Update index.md
  Extending/FileSystemProviders/Azure-Blob-Storage/index.md
Labels: category/umbraco-cms

#3183 Create signalR.md
  Implementation/Custom-Routing/signalR.md
Labels: category/umbraco-v9

#3186 Update index.md
  Extending/Macro-Parameter-Editors/index.md
Labels: category/needs-v8-docs, category/umbraco-cms
