Repository umbraco/UmbracoDocs, pull requests merged in 2021-05, with the labels that each got.

#3152 Incorrect code in CE example
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-cms

#3153 File system provider update
  Extending/FileSystemProviders/index-v9.md
  Umbraco9Articles.md
Labels: category/umbraco-cms

#3155 New Images
  images/code.png
  images/devices.png
  images/documents.png
  images/headless.png
  index.md
Labels: category/structure, category/umbraco-cms

#3161 Set correct udi value in member picker example
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
Labels: category/umbraco-cms

#3156 Tutorial: How to contribute a new versioned article
  Contribute/File-Naming-Conventions/index.md
  Contribute/How-to-add-a-new-verion/images/clone-your-fork.png
  Contribute/How-to-add-a-new-verion/images/submit-a-pull-request.png
  Contribute/How-to-add-a-new-verion/index.md
  Contribute/Pull-Requests/index.md
Labels: category/structure

#3165 New connection details feature
  Umbraco-Cloud/Databases/Cloud-Database/images/IPName.png
  Umbraco-Cloud/Databases/Cloud-Database/index.md
Labels: category/umbraco-cloud

#3162 Add missing step for beta in install steps
  Getting-Started/Setup/Install/install-umbraco-with-templates.md
Labels: category/umbraco-cms, category/umbraco-v9

#3166 Rename article and add images!
  Getting-Started/Setup/Install/images/VS/additional-info.png
  Getting-Started/Setup/Install/images/VS/configure-project.png
  Getting-Started/Setup/Install/images/VS/create-project.png
  Getting-Started/Setup/Install/images/VS/ready-solution.png
  Getting-Started/Setup/Install/images/VS/visual-studio-version-v9.png
  Getting-Started/Setup/Install/install-umbraco-with-visual-studio.md
Labels: category/umbraco-cms, category/umbraco-v9

#3163 add guide on running iis in v9
  Getting-Started/Setup/Server-Setup/iis-v9.md
  Getting-Started/Setup/Server-Setup/images/iis-module.png
  Getting-Started/Setup/Server-Setup/images/iis-site.png
  Getting-Started/Setup/Server-Setup/images/launchprofiles.png
  Getting-Started/Setup/Server-Setup/images/voila.png
Labels: category/umbraco-cms, category/umbraco-v9

#3158 Removing warning about rewrite not working on Cloudflare
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
Labels: category/umbraco-cloud

#3159 Added reference of additional configuration element introduced in Forms 8.7.2
  Add-ons/UmbracoForms/Developer/Configuration/index.md
Labels: category/pending-release, category/umbraco-forms

#3180 Resolve code samples to avoid leaving empty HTML tags
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textarea/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox/index.md
Labels: category/umbraco-cms

#3181 Updated to beta002
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-cms, category/umbraco-v9

#3173 Added details of UmbracoDeploy.Contrib to Umbraco Deploy installation documentation.
  Add-ons/Umbraco-Deploy/Installing-Deploy/Existing-site/index.md
Labels: category/umbraco-deploy

#3195 Change -P to -p
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-v9

#3194 Remove mentions of umbracoUseDirectoryUrls
  Reference/Config/umbracoSettings/index.md
Labels: category/umbraco-cms

#3200 Added link to named sections
  Getting-Started/Design/Templates/index.md
Labels: category/umbraco-cms

#3203 Backoffice-Infinite-Editing
  Getting-Started/Backoffice/Infinite-editing/index.md
Labels: category/umbraco-v9

#3206 Update trees-v9.md
  Extending/Section-Trees/trees-v9.md
Labels: category/umbraco-v9

#3106 Media Picker 3 documentation
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/images/Media-Picker3-Content.jpg
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/images/Media-Picker3-DataType.jpg
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md
  Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/pending-our-update, category/pending-release, category/umbraco-cms

#3189 Updated version (beta-002) in template install command
  Getting-Started/Setup/Install/install-umbraco-with-templates.md
Labels: category/umbraco-v9

#3202 Backoffice-Sections
  Getting-Started/Backoffice/Sections/index.md
Labels: category/pending-our-update, category/umbraco-v9

#3217 Updating config folder
  Extending/Dashboards/index-v9.md
  Extending/Section-Trees/trees-v9.md
Labels: category/umbraco-v9

#3221 Updated .NET Core info doc to have info about beta003
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-v9

#3215 Ipub Content Collections. Updated for v9.
  Reference/Querying/IPublishedContent/Collections/index-v9.md
  Reference/Querying/IPublishedContent/index-v9.md
Labels: category/umbraco-v9

#3213 Migrate events docs to notifications
  Extending/Section-Trees/trees-v9.md
  Reference/Events/ContentService-Events-v9.md
  Reference/Events/ContentTypeService-Events-v9.md
  Reference/Events/DataTypeService-Events-v9.md
  Reference/Events/EditorModel-Events/Customizing-the-links-box-v9.md
  Reference/Events/EditorModel-Events/index-v9.md
  Reference/Events/FileService-Events-v9.md
  Reference/Events/LocalizationService-Events-v9.md
  Reference/Events/MediaService-Events-v9.md
  Reference/Events/MediaTypeService-Events-v9.md
  Reference/Events/MemberService-Events/index-v9.md
  Reference/Events/MemberTypeService-Events-v9.md
  Reference/Events/determining-new-entity-v9.md
  Reference/Events/index-v9.md
Labels: category/umbraco-v9

#3222 Events --> Notifications
  Reference/Events/ContentService-Events.md
  Reference/Events/ContentTypeService-Events.md
  Reference/Events/DataTypeService-Events.md
  Reference/Events/EditorModel-Events/Customizing-the-links-box.md
  Reference/Events/EditorModel-Events/index.md
  Reference/Events/FileService-Events.md
  Reference/Events/LocalizationService-Events.md
  Reference/Events/MediaService-Events.md
  Reference/Events/MemberService-Events/index.md
  Reference/Events/determining-new-entity.md
  Reference/Events/index-v7.md
  Reference/Events/index.md
  Reference/Notifications/ContentService-Notifications.md
  Reference/Notifications/ContentTypeService-Notifications.md
  Reference/Notifications/DataTypeService-Notifications.md
  Reference/Notifications/EditorModel-Notifications/Customizing-the-links-box.md
  Reference/Notifications/EditorModel-Notifications/images/properties-info-app.png
  Reference/Notifications/EditorModel-Notifications/index.md
  Reference/Notifications/FileService-Notifications.md
  Reference/Notifications/LocalizationService-Notifications.md
  Reference/Notifications/MediaService-Notifications.md
  Reference/Notifications/MediaTypeService-Notifications.md
  Reference/Notifications/MemberService-Notifications/index.md
  Reference/Notifications/MemberTypeService-Notifications.md
  Reference/Notifications/determining-new-entity.md
  Reference/Notifications/index.md
Labels: category/umbraco-v9

#3224 Fix article
  Fundamentals/Data/Scheduled-Publishing/index.md
Labels: category/umbraco-v9

#3225 Updated article for V9
  Fundamentals/Data/Defining-content/images/v8Screenshots/createDoctype.PNG
  Fundamentals/Data/Defining-content/index.md
Labels: category/umbraco-v9

#3227 Minor fixes for V9
  Fundamentals/Data/Users/index.md
Labels: category/umbraco-v9

#3226 Updated article for V9
  Fundamentals/Backoffice/Content-Templates/index.md
Labels: category/umbraco-v9

#3228 Updated article for v9
  Fundamentals/Data/Data-Types/index.md
Labels: category/umbraco-v9

#3230 Updated article for V9
  Fundamentals/Data/Creating-Media/images/media-section.png
  Fundamentals/Data/Creating-Media/images/toggle-listview.png
  Fundamentals/Data/Creating-Media/images/v9-media-types-create1.png
  Fundamentals/Data/Creating-Media/images/v9-media-types-media-section.png
  Fundamentals/Data/Creating-Media/images/v9-media-types-upload-media.png
  Fundamentals/Data/Creating-Media/images/v9-media-types.png
  Fundamentals/Data/Creating-Media/index-vpre8.13.md
  Fundamentals/Data/Creating-Media/index.md
Labels: category/umbraco-v9

#3204 Update index-v9.md
  Extending/Database/images/db-table.png
  Extending/Database/index-v9.md
Labels: category/umbraco-v9

#3233 Added verified against metadata
  Tutorials/Creating-a-Custom-Dashboard/index.md
Labels: category/umbraco-v9

#3219 Added AzureDevOps Deploy example.
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-github-actions.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/index.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/Existing-site/index.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/New-site/index.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/index.md
Labels: category/umbraco-deploy

#3237 Added versionTo metadata
  Fundamentals/Backoffice/Content-Templates/index.md
  Fundamentals/Backoffice/Infinite-editing/index.md
  Fundamentals/Backoffice/Login/index.md
  Fundamentals/Backoffice/Sections/index.md
  Fundamentals/Backoffice/Variants/index.md
  Fundamentals/Data/Data-Types/index.md
  Fundamentals/Data/Defining-content/index.md
  Fundamentals/Data/Scheduled-Publishing/index.md
  Fundamentals/Data/Users/index.md
  Fundamentals/Design/Templates/index.md
Labels: category/umbraco-v9
