Repository umbraco/UmbracoDocs, pull requests merged in 2021-10, with the labels that each got.

#3403 Update default imaging settings
  Reference/V9-Config/ImagingSettings/index.md
Labels: category/pending-release, category/umbraco-v9

#3520 Fixed a broad range of typo's in v9 notification pages
  Reference/Events/index.md
  Reference/Notifications/ContentService-Notifications.md
  Reference/Notifications/ContentTypeService-Notifications.md
  Reference/Notifications/Creating-And-Publishing-Notifications.md
  Reference/Notifications/EditorModel-Notifications/index.md
  Reference/Notifications/MediaService-Notifications.md
  Reference/Notifications/MediaTypeService-Notifications.md
  Reference/Notifications/MemberTypeService-Notifications.md
  Reference/Notifications/index.md
Labels: hacktoberfest-accepted

#3522 V9 : Data persistence
  Implementation/Data-Persistence/index-v8.md
  Implementation/Data-Persistence/index.md
Labels: category/umbraco-v9

#3502 Updated "Working with Mac - Cloud" article for v9
  Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/images/clone-project.png
  Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index-v7.md
  Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index.md
Labels: category/umbraco-v9

#3482 Updated the IIS rewrites article for V9
  Reference/Routing/IISRewriteRules/index-v6.md
  Reference/Routing/IISRewriteRules/index.md
Labels: category/umbraco-v9

#3485 Add V9 common pitfalls
  Reference/Common-Pitfalls/index-v7.md
  Reference/Common-Pitfalls/index.md
Labels: category/umbraco-v9

#3507 Jonathan v9 cloud branch
  Umbraco-Cloud/Cloud-API/index.md
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/V9-files.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/V9-project-file.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/add-new.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/class-library.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/new-project.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/save-as.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/images/solution-VS.png
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index-v8.md
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
  Umbraco-Cloud/Upgrades/Product-Dependencies/index.md
  Umbraco-Cloud/index.md
Labels: category/umbraco-cloud, category/umbraco-v9

#3531 Added field type to the rechapta for forms examples
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha2/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha3/index.md
Labels: category/umbraco-forms, category/umbraco-v9

#3604 Updating Dashboard section
  Extending/Dashboards/index.md
Labels: category/umbraco-v9

#3605 Added a note for minified js files
  Extending/Backoffice-UI-API-Documentation/index.md
Labels: category/umbraco-v9

#3606 Backoffice search, code samples updated and verified against v9
  Extending/Backoffice-Search/index.md
Labels: category/umbraco-v9
