Repository umbraco/UmbracoDocs, pull requests merged in 2021-11, with the labels that each got.

#3618 Common pitfalls/add links to sigletons and statics
  Reference/Common-Pitfalls/index-v7.md
  Reference/Common-Pitfalls/index.md
Labels: category/umbraco-cms

#3584 Added updates for functionality due in Forms 8.9/9.1 and Deploy 4.4/9.1.
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
  Add-ons/Umbraco-Deploy/Deployment-Workflow/Restoring-Content/index.md
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index-v7.md
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Conditional-Logic/index.md
  Add-ons/UmbracoForms/Editor/Viewing-and-Exporting-Entries/index.md
Labels: category/umbraco-forms, category/pending-release, category/umbraco-deploy

#3623 Removed v9 articles for package actions and added a note for V8
  Extending/Packages/Package-Actions/custom-package-actions-v8.md
  Extending/Packages/Package-Actions/custom-package-actions.md
  Extending/Packages/Package-Actions/index-v8.md
  Extending/Packages/Package-Actions/index.md
Labels: category/umbraco-cms

#3241 Templating/Macros. Adjusted for v9. Modified code samples
  Reference/Templating/Macros/index-v9.md
Labels: category/umbraco-v9

#3599 Integration-Testing
  Implementation/Integration-Testing/index.md
  Implementation/index.md
Labels: category/pending-release, category/umbraco-cms, category/umbraco-v9

#3585 V9 version of Unit Testing Documentation
  Implementation/Unit-Testing/index-v8.md
  Implementation/Unit-Testing/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted

#3630 Added detail on registering custom udis
  Add-ons/Umbraco-Deploy/Extending/index.md
Labels: category/umbraco-v9, category/umbraco-deploy

#3621 Added a Tutorial: Custom views for block list
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Advanced.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Block-settings.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Catalogue-appearance.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Content-block-list.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Editor-appearance.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Feature-Content.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Feature-Options.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Feature-Settings.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Settings-option.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/Stylesheet-location.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/View-location.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/blocklist-editor-settings.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/data-models.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/document-properties.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/document-type.png
  Tutorials/Creating-Custom-Views-for-Blocklist/images/prevalue-options.png
  Tutorials/Creating-Custom-Views-for-Blocklist/index.md
Labels: category/umbraco-cms

#3625 Update Routing
  Reference/Routing/WebApi/routing.md
Labels: category/umbraco-v9

#3638 Change the Default Controller
  Implementation/Default-Routing/Controller-Selection/index.md
Labels: category/umbraco-v9

#3572 Updated code example to also check on http://
  Reference/Routing/Request-Pipeline/IContentFinder-v8.md
Labels: category/umbraco-cms, hacktoberfest-accepted

#3639 Use constant for WriterGroup
  Extending/Dashboards/index.md
Labels: category/umbraco-v9
