Repository umbraco/UmbracoDocs, pull requests merged in 2021-06, with the labels that each got.

#3244 Add outgoing IPs for new Cloud Infrastructure
  Umbraco-Cloud/Set-Up/External-Services/index.md
Labels: category/umbraco-cloud

#3201 Added information about ModelsBuilder VSIX and Umbraco Id
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
Labels: category/umbraco-cloud

#3248 Subscribing to notifications documentation
  Fundamentals/Code/Subscribing-To-Notifications/images/log-message.png
  Fundamentals/Code/Subscribing-To-Notifications/images/log-messages.png
  Fundamentals/Code/Subscribing-To-Notifications/images/log-viewer.png
  Fundamentals/Code/Subscribing-To-Notifications/index.md
  Reference/Notifications/index.md
Labels: category/umbraco-v9

#3229 Creating new section about deploy operations available from the deploy dashboard
  Umbraco-Cloud/Deployment/Deploy-Operations/Clearing-cached-signatures/images/clear-cached-signatures.gif
  Umbraco-Cloud/Deployment/Deploy-Operations/Clearing-cached-signatures/index.md
  Umbraco-Cloud/Deployment/Deploy-Operations/Deploy-schema/images/schema-deployments.gif
  Umbraco-Cloud/Deployment/Deploy-Operations/Deploy-schema/index.md
  Umbraco-Cloud/Deployment/Deploy-Operations/Extract-schema-to-data-files/images/generating-uda-files.gif
  Umbraco-Cloud/Deployment/Deploy-Operations/Extract-schema-to-data-files/index.md
  Umbraco-Cloud/Deployment/Deploy-Operations/images/locate-deploy-dashboard.gif
  Umbraco-Cloud/Deployment/Deploy-Operations/index.md
  Umbraco-Cloud/Set-Up/Power-Tools/Generating-UDA-files/index.md
  Umbraco-Cloud/Set-Up/Power-Tools/Manual-extractions/index.md
Labels: category/umbraco-cloud, category/umbraco-deploy

#3251 Update to regex to handle mp* files
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
Labels: category/umbraco-cloud

#3275 Fix broken links
  README.md
Labels: category/broken-link

#3262 Updated Fundamentals/Setup/Upgrading to v9
  Fundamentals/Setup/Upgrading/general-v9.md
  Fundamentals/Setup/Upgrading/index-v9.md
  Fundamentals/Setup/Upgrading/version-specific.md
  Fundamentals/Setup/index-v9.md
Labels: category/umbraco-v9

#3272 Update UmbracoServices to v9
  Fundamentals/Code/Umbraco-Services/index-v9.md
  Reference/Management/Services/AuditService/index-v9.md
  Reference/Management/Services/ConsentService/index-v9.md
  Reference/Management/Services/ContentService/index-v9.md
  Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers-v9.md
  Reference/Management/Services/ContentTypeService/Retrieving-content-types-v9.md
  Reference/Management/Services/ContentTypeService/index-v9.md
  Reference/Management/Services/DataTypeService/index-v9.md
  Reference/Management/Services/EntityService/index-v9.md
  Reference/Management/Services/FileService/index-v9.md
  Reference/Management/Services/LocalizationService/Retrieving-languages-v9.md
  Reference/Management/Services/LocalizationService/index-v9.md
  Reference/Management/Services/MacroService/index-v9.md
  Reference/Management/Services/MediaService/index-v9.md
  Reference/Management/Services/MemberGroupService/index-v9.md
  Reference/Management/Services/MemberService/index-v9.md
  Reference/Management/Services/MemberTypeService/index-v9.md
Labels: category/umbraco-v9

#3267 Cloud migration documentation
  Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/images/CMS-version-on-Umbraco-Cloud-project_1094x291.jpg
  Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/index.md
  Umbraco-Cloud/Upgrades/index.md
Labels: category/umbraco-cloud

#3271 Update on Media-Picker-3/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md
Labels: category/code-example

#3276 Update index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
Labels: category/code-example

#3273 Update determining-new-entity.md
  Reference/Events/determining-new-entity.md
Labels: category/code-example

#3279 Updated Azure web apps to v9
  Fundamentals/Setup/Server-Setup/azure-web-apps-v9.md
Labels: category/umbraco-v9

#3223 add nc example
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v7.md
Labels: category/code-example, category/umbraco-cms

#3212 ModelsBuilder Configuration
  Reference/Templating/Modelsbuilder/configuration-v9.md
  Reference/Templating/Modelsbuilder/images/ModelsBuilderDashboard-v9.png
Labels: category/umbraco-v9

#3280 Migrate creating forms to v9
  Fundamentals/Code/Creating-Forms/index-v9.md
Labels: category/umbraco-v9

#3286 Migrate models builder docs to v9
  Reference/Templating/Modelsbuilder/Builder-Modes-v9.md
  Reference/Templating/Modelsbuilder/CoolThingsWithModels-v9.md
  Reference/Templating/Modelsbuilder/Introduction-v9.md
  Reference/Templating/Modelsbuilder/Understand-And-Extend-v9.md
  Reference/Templating/Modelsbuilder/Using-Interfaces-v9.md
  Reference/Templating/Modelsbuilder/index-v9.md
Labels: category/umbraco-v9

#3289 Prepared for beta4 to go out tuesday
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-v9

#3278 V9 Configuration documentation
  Reference/V9-Config/ConnectionStringsSettings/index-v9.md
  Reference/V9-Config/ContentSettings/index-v9.md
  Reference/V9-Config/DebugSettings/index-v9.md
  Reference/V9-Config/ExamineSettings/index-v9.md
  Reference/V9-Config/ExceptionFilterSettings/index-v9.md
  Reference/V9-Config/GlobalSettings/index-v9.md
  Reference/V9-Config/HealthChecks/index-v9.md
  Reference/V9-Config/HostingSettings/index-v9.md
  Reference/V9-Config/ImagingSettings/index-v9.md
  Reference/V9-Config/KeepAliveSettings/index-v9.md
  Reference/V9-Config/LoggingSettings/index-v9.md
  Reference/V9-Config/ModelsBuilderSettings/index-v9.md
  Reference/V9-Config/NuCacheSettings/index-v9.md
  Reference/V9-Config/PluginsSettings/index-v9.md
  Reference/V9-Config/RequestHandlerSettings/index-v9.md
  Reference/V9-Config/RichTextEditorSettings/index-v9.md
  Reference/V9-Config/RuntimeMinificationSettings/index-v9.md
  Reference/V9-Config/RuntimeSettings/index-v9.md
  Reference/V9-Config/SecuritySettings/index-v9.md
  Reference/V9-Config/Serilog/index-v9.md
  Reference/V9-Config/ToursSettings/index-v9.md
  Reference/V9-Config/TypeFinderSettings/index-v9.md
  Reference/V9-Config/UnattendedSettings/index-v9.md
  Reference/V9-Config/WebRoutingSettings/index-v9.md
  Reference/V9-Config/index-v9.md
Labels: category/umbraco-v9

#3288 Update data type definition for v8
  Reference/Management/Models/DataType-v6.md
  Reference/Management/Models/DataType.md
  Reference/Management/Models/index.md
Labels: category/umbraco-cms

#3290 Create dictionary item article
  Reference/Management/Models/DictionaryItem.md
  Reference/Management/Models/index.md
Labels: category/umbraco-cms

#3292 Create reference management models template
  Reference/Management/Models/Language.md
  Reference/Management/Models/Template.md
  Reference/Management/Models/index.md
Labels: category/umbraco-cms

#3236 Backoffice-Login
  Fundamentals/Backoffice/Login/index-v9.md
Labels: category/umbraco-v9

#3253 Creating a package
  Extending/Packages/Creating-a-Package/images/creating-package-menu-v9.png
  Extending/Packages/Creating-a-Package/index-v9.md
Labels: category/umbraco-v9
