Repository umbraco/UmbracoDocs, pull requests merged in 2021-08, with the labels that each got.

#3319 Updated article for v9
  Fundamentals/Data/Data-Types/default-data-types-v9.md
  Fundamentals/Data/Data-Types/images/default-data-types-9.png
Labels: category/umbraco-v9

#3337 Updated Starter Kit Tutorial
  Tutorials/Starter-kit/Index.md
  Tutorials/Starter-kit/Lessons/1-Customise-the-Starter-Kit/index.md
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-2.md
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-3.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/index.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-1.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-2.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-3-v9.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4-v9.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/summary.md
  Tutorials/Starter-kit/Lessons/index.md
Labels: category/umbraco-v9

#3379 Updated create a database table article for V9
  Extending/Database/index-v9.md
Labels: category/umbraco-v9

#3310 Forms Themes
  Add-ons/UmbracoForms/Developer/Rendering-Scripts/index-v9.md
  Add-ons/UmbracoForms/Developer/Themes/index-v9.md
Labels: category/umbraco-v9

#3386 V9 Logging Updates
  Fundamentals/Code/Debugging/Logging/index-v9.md
  Reference/V9-Config/Serilog/index.md
Labels: category/umbraco-v9

#3388 Update the way to get querystring variables in the index method
  Reference/Routing/custom-controllers-v9.md
Labels: category/umbraco-v9

#3387 Updated Setting up Visual Studio Code section
  Extending/Property-Editors/images/JSON-schema.png
  Extending/Property-Editors/package-manifest-v9.md
Labels: category/umbraco-v9

#3393 Added Changes between rc 1 and rc 2
  UmbracoNetCoreUpdates.md
Labels: category/umbraco-v9

#3372 Updates for upcoming Forms and Deploy minor releases
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v9.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
  Add-ons/Umbraco-Deploy/Extending/index.md
  Add-ons/UmbracoForms/Developer/Configuration/index-v9.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/MessageOnSubmit.png
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/index.md
  Add-ons/UmbracoForms/Editor/Viewing-and-Exporting-Entries/index.md
Labels: category/umbraco-forms, category/pending-release, category/umbraco-deploy

#3385 Rename TagService to CacheTagService
  Reference/Cache/Examples/tags.md
Labels: category/umbraco-cms

#3373 Reference umbraco mapper
  Reference/Mapping/index-v9.md
Labels: category/umbraco-v9

#3404 Add filesystem providers to V9 Config section
  Reference/V9-Config/filesystemProviders-v9.md
  Reference/V9-Config/index.md
Labels: category/umbraco-v9

#3409 Updated the section about migrating v7 projects.
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Labels: category/umbraco-cloud

#3309 Rendering content
  Fundamentals/Design/Rendering-Content/images/query-v9.png
  Fundamentals/Design/Rendering-Content/index-v9.md
Labels: category/umbraco-v9

#3371 Added v9 guide to add 404 error page
  Tutorials/Custom-Error-Pages/index-v9.md
Labels: category/umbraco-v9

#3421 New shop article
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/Payment_methods.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/change-payment.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/invoice.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/manage-subscriptions-new.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/payment-history.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/payment-settings.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/select_payment.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/images/subscriptions.png
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/index.md
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/new-shop-index.md
Labels: category/umbraco-cloud

#3426 V9: Added Cache docs, updated from v7.
  Reference/Cache/cache-refresher-v9.md
  Reference/Cache/index-v9.md
  Reference/Cache/updating-cache-v9.md
Labels: category/umbraco-v9

#3367 Update trees-v9.md
  Extending/Section-Trees/trees-v9.md
Labels: category/umbraco-v9

#3414 Update Code sample with valid JSON
  Reference/V9-Config/RequestHandlerSettings/index.md
Labels: category/umbraco-v9
