Repository umbraco/UmbracoDocs, pull requests merged in 2022-09, with the labels that each got.

#4329 Updated articles to reflect that we now have to regions available.
  Umbraco-Cloud/Frequently-Asked-Questions/index.md
  Umbraco-Cloud/Getting-Started/Baselines/index.md
Labels: category/umbraco-cloud

#4328 New article: Migrate between Cloud regions
  Umbraco-Cloud/Getting-Started/Migrate-between-regions/images/CreateProject-SelectRegion.png
  Umbraco-Cloud/Getting-Started/Migrate-between-regions/index.md
Labels: category/umbraco-cloud, category/pending-release

#4332 Updated from cloud FAQ for regional support
  Umbraco-Cloud/Frequently-Asked-Questions/index.md
Labels: category/umbraco-cloud

#4333 No example of HttpPostedFileBase
  Reference/Management/Services/MediaService/Index.md
Labels: category/umbraco-cms

#4325 Added a page on installing and uninstalling packages
  Extending/Packages/Installing-And-Uninstalling-Packages/images/app-plugins-starterkit.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/backoffice-installed-packages.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/backoffice-packages-section-package.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/backoffice-packages-section.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/installed-package-leftovers-backoffice.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/nuget-installing-options.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/nuget-package-in-manager.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-content.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-datatypes.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-document-types.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-media.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-partials.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/removing-templates.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/seochecker-after-removal.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/seochecker-app-plugins.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/seochecker-content-section.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/uninstalling-via-nuget-package-manager.png
  Extending/Packages/Installing-And-Uninstalling-Packages/images/vs-cleaning-solution.png
  Extending/Packages/Installing-And-Uninstalling-Packages/index.md
Labels: category/umbraco-cms

#4338 Fixing typo
  Umbraco-Cloud/Set-Up/Usage/index.md
Labels: category/grammar

#4347 Update index.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
Labels: category/umbraco-forms

#4353 Updated Note
  Fundamentals/Code/Subscribing-To-Events/index.md
Labels: category/umbraco-cms

#4346 Small fixes
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Labels: category/umbraco-cms

#4357 Added a word
  Fundamentals/Setup/Install/installing-nightly-builds.md
Labels: category/umbraco-cms

#4362 Fixed incorrect configuration key
  Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
Labels: category/umbraco-deploy

#4303 Migrating Plumber docs
  Add-ons/Umbraco-Plumber/Approval-Groups/images/Approval-group-settings.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/Approval-groups.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/Create-approval-group.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/Inherited-group-membership.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/add-group-member.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/approval-group-history.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/approval-group-members.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/approval-groups-role.png
  Add-ons/Umbraco-Plumber/Approval-Groups/images/details-overlay.png
  Add-ons/Umbraco-Plumber/Approval-Groups/index.md
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/images/Buttons.png
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/images/Default_Buttons.png
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/images/WorkflowDashboard_ContentSection.png
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/images/WorkflowDashboard_WorkflowSection.png
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/images/blocked_content.png
  Add-ons/Umbraco-Plumber/Dashboards-and-Buttons/index.md
  Add-ons/Umbraco-Plumber/Email-Templates/index.md
  Add-ons/Umbraco-Plumber/Events/index.md
  Add-ons/Umbraco-Plumber/Getting-Started/index.md
  Add-ons/Umbraco-Plumber/Installing-Plumber/images/VS_Installation.png
  Add-ons/Umbraco-Plumber/Installing-Plumber/images/Workflow_dashboard.png
  Add-ons/Umbraco-Plumber/Installing-Plumber/images/Workflow_section.png
  Add-ons/Umbraco-Plumber/Installing-Plumber/index.md
  Add-ons/Umbraco-Plumber/Licensing/images/lic.png
  Add-ons/Umbraco-Plumber/Licensing/index.md
  Add-ons/Umbraco-Plumber/Notifications-and-Reminders/images/Notifications_tab.png
  Add-ons/Umbraco-Plumber/Notifications-and-Reminders/index.md
  Add-ons/Umbraco-Plumber/Upgrading-Plumber/index.md
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/Active-workflow-initiate-request.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/Active_Workflow_detailed_info.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/Configuration-sub-section.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/Details-overlay.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/History-sub-section.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/approval-flow-types.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/approval-groups-roles.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/content-app.png
  Add-ons/Umbraco-Plumber/Workflow-Content-App/images/content-approval-flow.gif
  Add-ons/Umbraco-Plumber/Workflow-Content-App/index.md
  Add-ons/Umbraco-Plumber/Workflow-History/images/history-detail-button.png
  Add-ons/Umbraco-Plumber/Workflow-History/images/history-filter.png
  Add-ons/Umbraco-Plumber/Workflow-History/images/history-pagesize.png
  Add-ons/Umbraco-Plumber/Workflow-History/images/workflow-history.png
  Add-ons/Umbraco-Plumber/Workflow-History/index.md
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/add-approval-flow.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/add-doc-type-approval-flows-settings.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/add-doc-type-approval-flows.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/doc-type-approval-flows.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/edit-doc-type-approval-flows-settings.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/edit-doc-type-approval-flows.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/exclude-nodes.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/general-settings.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/new-node-approval-flow.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/select-content-from-tree.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/images/workflow-settings.png
  Add-ons/Umbraco-Plumber/Workflow-Settings/index.md
  Add-ons/Umbraco-Plumber/index.md
  Add-ons/index.md
Labels: category/umbraco-plumber, dteam/review

#4367 Added missing Heartcore GraphQL types
  Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/index.md
  Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
Labels: category/umbraco-heartcore

#4370 Added note about how and when to use global settings
  Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced.md
Labels: category/umbraco-cms

#4374 Updated the position of the search field
  Umbraco-Cloud/Troubleshooting/Deployments/Dependency-Exceptions/index.md
Labels: category/umbraco-cloud

#4365 New article: 2-factor authentication on Cloud
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/Phone-auth.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/auth-app.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/auth-app2.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/email-auth.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/email-auth2.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/images/email-auth3.png
  Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
Labels: category/umbraco-cloud

#4375 Updated docs since 9.4 to recommend using FileSystemMainDomLock
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v9.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
Labels: category/umbraco-cms

#4334 v10.2: Permissions on Variants
  Fundamentals/Backoffice/Variants/images/Assign-Access-Languages.png
  Fundamentals/Backoffice/Variants/images/invariant-property-locked.png
  Fundamentals/Backoffice/Variants/index.md
  Fundamentals/Data/Dictionary-Items/index.md
  Fundamentals/Data/Users/images/create-user-group.png
  Fundamentals/Data/Users/images/default-permissions.png
  Fundamentals/Data/Users/index.md
Labels: category/umbraco-cms, dteam/review

#4335 v10.2: New AllowEditInvariantFromNonDefault setting
  Reference/Configuration/SecuritySettings/index.md
Labels: category/umbraco-cms, dteam/review

#4360 Add note about the supportsReadOnly mode config
  Extending/Property-Editors/Package-Manifest/index.md
  Tutorials/Creating-a-Property-Editor/index.md
Labels: category/umbraco-cms, dteam/review

#4326 Update IPublishedContentQuery to use proper standards
  Reference/Querying/IPublishedContentQuery/index.md
  Reference/Querying/index.md
Labels: category/umbraco-cms, dteam/review

#4324 Update backoffice search documentation
  Extending/Backoffice-Search/index.md
Labels: category/umbraco-cms, dteam/review

#4378 Update to 'Adding a type to the provider model'
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
Labels: category/umbraco-forms

#4320 Update multisearcher documentation
  Reference/Searching/Examine/pdfindex-multisearcher-v8.md
  Reference/Searching/Examine/pdfindex-multisearcher.md
Labels: category/umbraco-cms, dteam/review

#4380 Added an 's' to Acces
  Umbraco-Heartcore/API-Documentation/Redirect/index.md
Labels: category/umbraco-heartcore

#4381 Adding the new Caption to the PreValue example
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Prevaluesourcetype.md
Labels: category/umbraco-forms

#4379 Fixes Issue 4361
  Reference/Routing/Umbraco-API-Controllers/index.md
Labels: category/umbraco-cms

#4319 v9 & v10: Examine custom indexing
  Reference/Searching/Examine/Indexing/index-v8.md
  Reference/Searching/Examine/Indexing/index.md
Labels: category/umbraco-cms, dteam/review

#4384 Update index.md
  Reference/Configuration/RuntimeSettings/index.md
Labels: category/umbraco-cms

#4385 New Cloud Release notes (2022-09-19-ReleaseNotes)
  Umbraco-Cloud/Release-Notes/2022-09-19-ReleaseNotes.md
  Umbraco-Cloud/Release-Notes/images/2FA-Registration.gif
  Umbraco-Cloud/Release-Notes/images/Phone-auth.png
  Umbraco-Cloud/Release-Notes/images/ProjectsDashboardV1.gif
  Umbraco-Cloud/Release-Notes/images/USRegionRegistration.gif
  Umbraco-Cloud/Release-Notes/index.md
Labels: category/umbraco-cloud

#4318 added notes about new changes to tls/ca
  Umbraco-Cloud/Set-Up/Manage-Hostnames/ca-record-migration.md
  Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Labels: category/umbraco-cloud, dteam/review

#4336 update activity log function
  Tutorials/Creating-a-Custom-Dashboard/index.md
Labels: category/umbraco-cms

#4387 Cleanup some vale warnings
  Add-ons/Umbraco-Deploy/Deployment-Workflow/Deploying-Deletions/index.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v8.md
  Reference/Searching/Examine/examine-events.md
  Tutorials/Creating-a-Custom-Dashboard/index.md
Labels: category/styleguide

#4389 UmbracoPath is no longer configurable
  Reference/Configuration/GlobalSettings/index.md
  Reference/Security/Security-hardening/index-v9.md
  Reference/Security/Security-hardening/index.md
Labels: category/umbraco-cms

#4386 Add note about CopyRazorGenerateFilesToPublishDirectory
  Fundamentals/Setup/Server-Setup/runtime-modes.md
Labels: category/umbraco-cms

#4390 Removed version 9-10 version of the Media Picker article
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index-v7.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index-v8.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index-vpre8.1.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md
Labels: category/structure, category/umbraco-cms

#4399 add custom formats dropdown example
  Reference/Configuration/RichTextEditorSettings/index.md
Labels: category/umbraco-cms

#4401 Update index.md
  Umbraco-Cloud/Security/index.md
Labels: category/umbraco-cloud

#4342 Add tutorial for caching of static assets
  Tutorials/Cache-Static-Assets/index.md
  Tutorials/index.md
Labels: category/umbraco-cms, dteam/review

#4404 New certificate authority documentation
  Umbraco-Cloud/Set-Up/Manage-Hostnames/ca-record-migration.md
  Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Labels: category/umbraco-cloud

#4402 Updated AD article to include Member information
  Reference/Security/Authenticate-with-Active-Directory/images/AD_Login.png
  Reference/Security/Authenticate-with-Active-Directory/images/AD_Login_Members.png
  Reference/Security/Authenticate-with-Active-Directory/index.md
Labels: category/umbraco-cms

#4406 Small changes to the prevalues article
  Add-ons/UmbracoForms/Editor/Defining-and-Attaching-Prevaluesources/images/Prevalues-with-caption.png
  Add-ons/UmbracoForms/Editor/Defining-and-Attaching-Prevaluesources/index.md
Labels: category/umbraco-forms

#4408 Add tip on check for the CAA record
  Umbraco-Cloud/Set-Up/Manage-Hostnames/ca-record-migration.md
Labels: category/umbraco-cloud

#4400 Avoid using EnsureUmbracoContext in a loop
  Implementation/Services/index-v8.md
  Implementation/Services/index.md
Labels: category/umbraco-cms, dteam/review

#4403 Fixes Issue 4391
  Implementation/Custom-Routing/index.md
  Implementation/Custom-Routing/signalR.md
Labels: category/umbraco-cms

#4409 Merged Hyperbolic into Editorializing
  .github/styles/UmbracoDocs/Editorializing.yml
  .github/styles/UmbracoDocs/Hyperbolic.yml
Labels: category/styleguide

#4411 Fixes Issue 4405
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
Labels: category/umbraco-forms

#4410 Adding more rules and extending existing ones
  .github/styles/UmbracoDocs/Brands.yml
  .github/styles/UmbracoDocs/Names.yml
  .github/styles/UmbracoDocs/Terms.yml
  .github/styles/UmbracoDocs/UmbracoTerms.yml
Labels: category/styleguide

#4413 Update Styleguide article in Contribution section
  CONTRIBUTING.md
  Contribute/Style-Guide/index.md
  Contribute/index.md
Labels: category/styleguide

#4412 Added rule that catches whether an acronym has been defined
  .github/styles/UmbracoDocs/Acronyms.yml
  Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced.md
  Fundamentals/Setup/Server-Setup/permissions-v10.md
  Umbraco-Cloud/Troubleshooting/troubleshooting-frontend.md
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
  Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
  Umbraco-Heartcore/API-Documentation/index.md
  Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md
  Umbraco-Heartcore/Getting-Started-Cloud/Webhooks/index.md
  Umbraco-Heartcore/Tutorials/Creating-A-Custom-Grid-Editor/index.md
Labels: category/styleguide

#4415 Add section about the acronym rule to the style guide contrib
  Contribute/Style-Guide/index.md
Labels: category/styleguide
