Repository umbraco/UmbracoDocs, pull requests merged in 2022-06, with the labels that each got.

#4021 Verified Editor's Manual Tutorial for v10
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Copying-a-Page/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Deleting-and-Restoring-Pages/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Editing-Existing-Content/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Finding-Content/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Logging-In-and-Out/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Moving-a-Page/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Ordering-Pages/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Umbraco-Interface/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/index.md
  Tutorials/Editors-Manual/Media-Management/Cropping-Images/index.md
  Tutorials/Editors-Manual/Media-Management/Working-with-Folders/index.md
  Tutorials/Editors-Manual/Media-Management/Working-with-Images-and-Files/index.md
  Tutorials/Editors-Manual/Media-Management/index.md
  Tutorials/Editors-Manual/Tips-and-Tricks/Audit-Trail/index.md
  Tutorials/Editors-Manual/Tips-and-Tricks/Preview-Pane-Responsive-View/index-v7.md
  Tutorials/Editors-Manual/Tips-and-Tricks/Preview-Pane-Responsive-View/index.md
  Tutorials/Editors-Manual/Tips-and-Tricks/Session-Timeout/index.md
  Tutorials/Editors-Manual/Tips-and-Tricks/Tips-when-Working-with-Folders/index.md
  Tutorials/Editors-Manual/Version-Management/Comparing-Versions/images/Rollback-changes-v10.png
  Tutorials/Editors-Manual/Version-Management/Comparing-Versions/index.md
  Tutorials/Editors-Manual/Version-Management/Rollback-to-a-Previous-Versions/images/Rollback-changes-v10.png
  Tutorials/Editors-Manual/Version-Management/Rollback-to-a-Previous-Versions/index.md
  Tutorials/Editors-Manual/Version-Management/index.md
  Tutorials/Editors-Manual/Working-with-Content/index.md
  Tutorials/Editors-Manual/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4002 Verify Content Apps article for v10
  Extending/Content-Apps/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4017 Updated 2FA article for v10
  Reference/Security/Two-factor-authentication/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4029 v10: Verify "Creating Media" article
  Fundamentals/Data/Creating-Media/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4025 Updated "Multisite setup" tutorial for v10
  Tutorials/Multisite-Setup/images/2-culturehostnames-v10.png
  Tutorials/Multisite-Setup/images/3-culturehostnamesp2-v10.png
  Tutorials/Multisite-Setup/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4024 Updated "Creating a Multilingual Site" tutorial for v10
  Tutorials/Multilanguage-Setup/images/Language-variants-v10.png
  Tutorials/Multilanguage-Setup/images/adding-danish-language-v10.png
  Tutorials/Multilanguage-Setup/images/change-default-language-v10.png
  Tutorials/Multilanguage-Setup/images/fallback-language-v10.png
  Tutorials/Multilanguage-Setup/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4006 Verified Tracking article for v10
  Extending/Property-Editors/Tracking/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4033 v10: Verify "Label" article
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Label.md
Labels: category/umbraco-cms, category/umbraco-v10

#4034 v10: Member Picker
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4035 v10: Verify "Member Group Picker" article
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4042 Nested-content-property-editor-v10-update
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4037 Verified Rendering content article for v10
  Fundamentals/Design/Rendering-Content/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4038 Verified Named sections article for v10
  Fundamentals/Design/Templates/named-sections.md
Labels: category/umbraco-cms, category/umbraco-v10

#4043 Updated article for v10
  Fundamentals/Data/Members/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4044 Verified most Cloud articles for v10
  Umbraco-Cloud/Deployment/Cloud-to-Cloud/index.md
  Umbraco-Cloud/Deployment/Content-Transfer/index.md
  Umbraco-Cloud/Deployment/Deploying-Deletions/index.md
  Umbraco-Cloud/Deployment/Hotfixes/Move-files-manually/index.md
  Umbraco-Cloud/Deployment/Hotfixes/Using-Git/index.md
  Umbraco-Cloud/Deployment/Hotfixes/index.md
  Umbraco-Cloud/Deployment/Local-to-Cloud/index.md
  Umbraco-Cloud/Deployment/Restoring-content/Partial-Restore/index.md
  Umbraco-Cloud/Deployment/Restoring-content/index.md
  Umbraco-Cloud/Deployment/Umbraco-Forms-on-Cloud/index.md
  Umbraco-Cloud/Getting-Started/Baselines/Baseline-Merge-Conflicts/index.md
  Umbraco-Cloud/Getting-Started/Baselines/Break-baseline/index.md
  Umbraco-Cloud/Getting-Started/Baselines/Upgrading-Child-Projects/index.md
  Umbraco-Cloud/Getting-Started/Baselines/index.md
  Umbraco-Cloud/Getting-Started/Environments/index.md
  Umbraco-Cloud/Getting-Started/Project-Overview/index.md
  Umbraco-Cloud/Getting-Started/Team-Workflow-On-Cloud/index.md
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md
  Umbraco-Cloud/Getting-Started/index.md
  Umbraco-Cloud/Set-Up/Application-Insights/index.md
  Umbraco-Cloud/Set-Up/External-Services/index.md
  Umbraco-Cloud/Set-Up/Going-live/index.md
  Umbraco-Cloud/Set-Up/Manage-Environments/index.md
  Umbraco-Cloud/Set-Up/Manage-Subscriptions/index.md
  Umbraco-Cloud/Set-Up/SMTP-settings/index.md
  Umbraco-Cloud/Set-Up/Team-Members/Accounts-Contact.md
  Umbraco-Cloud/Set-Up/Team-Members/Technical-Contact.md
  Umbraco-Cloud/Set-Up/Team-Members/index.md
  Umbraco-Cloud/Set-Up/Upgrade-Umbraco-Cloud-Plan/index.md
  Umbraco-Cloud/Set-Up/Usage/index.md
  Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index.md
  Umbraco-Cloud/Troubleshooting/Log-files/Enable-Logging.md
  Umbraco-Cloud/Troubleshooting/Log-files/index.md
  Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#4046 v10: Verified "Create Form (MVC)"
  Fundamentals/Code/Creating-Forms/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4047 v10: Verify Users article
  Fundamentals/Data/Users/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4048 Verified Data Types article for v10
  Fundamentals/Data/Data-Types/images/creating-a-data-type-v10.png
  Fundamentals/Data/Data-Types/images/viewing-data-type-reference.png
  Fundamentals/Data/Data-Types/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4049 v10: Verify docs on Stylesheets and JS
  Fundamentals/Design/Stylesheets-Javascript/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4041 Added note about "deprecating" the Models docs.
  Reference/Management/Models/index.md
Labels: category/umbraco-cms

#4051 v10: Content Version Cleanup
  Fundamentals/Data/Content-Version-Cleanup/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4052 Verified Dictionary Items article for v10
  Fundamentals/Data/Dictionary-Items/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4054 Updated backoffice user manager docs
  Reference/Security/backoffice-user-manager.md
Labels: category/umbraco-cms, category/umbraco-v10

#4050 Verified Scheduled Publishing article for v10
  Fundamentals/Data/Scheduled-Publishing/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4056 v10: Verify a bunch of property editor docs
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/CheckBox-List/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/images/Color-Picker-DataType-v10.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Date-Time/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/images/definition-example-v10.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/list-view-settings1-v10.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/images/list-view-settings2-v10.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Listview/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/images/MediaPicker-DataType-v10.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4058 Verified Config Transforms article for v10
  Umbraco-Cloud/Set-Up/Config-Transforms/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#4059 Verified Media on Umbraco Cloud article for V10
  Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/index.md
  Umbraco-Cloud/Set-Up/Media/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#3291 Updating structure error documentation to troubleshoot with deploy dashboard
  Umbraco-Cloud/Troubleshooting/Deployments/Structure-Error/index.md
Labels: category/umbraco-deploy

#4063 v10: Add version labels to articles in Implementation section
  Implementation/Composing/index.md
  Implementation/Controllers/index.md
  Implementation/Custom-Routing/index.md
  Implementation/Data-Persistence/index.md
  Implementation/Default-Routing/Controller-Selection/index.md
  Implementation/Default-Routing/Execute-Request/index.md
  Implementation/Default-Routing/Inbound-Pipeline/index.md
  Implementation/Default-Routing/index.md
  Implementation/Integration-Testing/index.md
  Implementation/Services/Circular-Dependencies/index.md
  Implementation/Services/index.md
  Implementation/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4061 Updated the Member registration and login tutorial for v10
  Tutorials/Members-Registration-And-Logins/index-v10.md
Labels: category/umbraco-cms, category/umbraco-v10

#4067 Updated Reference Routing Authorized to v10
  Reference/Routing/Authorized/index.md
Labels: category/umbraco-v10

#4068 Updated Reference>Routing>Request Pipeline> Outbound pipeline to v10
  Reference/Routing/Request-Pipeline/outbound-pipeline.md
Labels: category/umbraco-v10

#4073 v10: Add version labels on article in Extending
  Extending/Backoffice-Search/index.md
  Extending/Embedded-Media-Provider/index.md
  Extending/FileSystemProviders/Azure-Blob-Storage/index.md
  Extending/FileSystemProviders/index.md
  Extending/Packages/Creating-a-Package/index.md
  Extending/Packages/Creating-a-nuget-package/index.md
  Extending/Packages/Language-Files-For-Packages/index.md
  Extending/Packages/Maintaining-Packages/index.md
  Extending/Packages/Package-Actions/custom-package-actions.md
  Extending/Packages/Package-Actions/index.md
  Extending/Packages/Packages-on-Umbraco-Cloud/index.md
  Extending/Packages/Uploading-to-Our/index.md
  Extending/Packages/package-types.md
  Extending/Property-Editors/Declaring-your-property-editor.md
  Extending/Property-Editors/full-examples-value-converters.md
  Extending/Property-Editors/value-converters.md
Labels: category/umbraco-cms, category/umbraco-v10

#4074 v10: Adding version labels to articles related to breaking changes
  Extending/Database/index.md
  Extending/Property-Editors/Build-a-Block-Editor.md
  Extending/Section-Trees/tree-actions.md
  Fundamentals/Backoffice/LogViewer/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
  Reference/Configuration-for-Umbraco-7-and-8/Serilog/index.md
  Reference/Notifications/EditorModel-Notifications/Customizing-the-links-box.md
  Reference/Notifications/EditorModel-Notifications/index.md
  Reference/Notifications/MediaTypeService-Notifications/index.md
  Reference/Notifications/MemberService-Notifications/index.md
  Reference/Scheduling/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4075 v10: Update TryFindContent references
  Implementation/Services/index.md
  Reference/Routing/Request-Pipeline/IContentFinder.md
Labels: state/needs-investigation, category/umbraco-cms, category/umbraco-v10

#4022 Updated custom-route docs post 9.5 Release
  Reference/Routing/custom-routes.md
Labels: category/umbraco-cms

#4084 v10: Examine
  Reference/Searching/Examine/Indexing/index.md
  Reference/Searching/Examine/Quick-Start/index.md
  Reference/Searching/Examine/examine-events.md
  Reference/Searching/Examine/examine-management.md
  Reference/Searching/Examine/examine-manager.md
  Reference/Searching/Examine/index.md
  Reference/Searching/Examine/overview-explanation.md
  Reference/Searching/Examine/pdf-index.md
  Reference/Searching/Examine/terminology.md
  Reference/Searching/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4081 v10: Updated article on File/Folder permissions
  Fundamentals/Setup/Server-Setup/permissions-v10.md
Labels: category/umbraco-cms, category/umbraco-v10

#4086 v10: Verified User Picker article for v10
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/User-Picker/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4085 v10: Add verion labels and cleanup to Setup and Install sections
  Fundamentals/Setup/Install/Running-Umbraco-On-A-Mac.md
  Fundamentals/Setup/Install/iis.md
  Fundamentals/Setup/Install/index.md
  Fundamentals/Setup/Install/install-umbraco-with-nuget.md
  Fundamentals/Setup/Install/install-umbraco-with-templates-v9.md
  Fundamentals/Setup/Install/install-umbraco-with-templates.md
  Fundamentals/Setup/Install/install-umbraco-with-vs-code.md
  Fundamentals/Setup/Install/installing-nightly-builds.md
  Fundamentals/Setup/Install/visual-studio.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/index.md
  Fundamentals/Setup/Server-Setup/Load-Balancing/logging.md
  Fundamentals/Setup/Server-Setup/azure-web-apps.md
  Fundamentals/Setup/Server-Setup/iis/index.md
  Fundamentals/Setup/Server-Setup/index.md
  Fundamentals/Setup/Upgrading/general.md
  Fundamentals/Setup/Upgrading/index.md
  Fundamentals/Setup/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4079 v10: Source control
  Fundamentals/Code/Source-Control/images/file-structure-v10.png
  Fundamentals/Code/Source-Control/index-v10.md
Labels: category/umbraco-cms, category/umbraco-v10

#4071 v10: Created new article for Nullable reference types
  Implementation/Nullable-Reference-Types/index.md
Labels: state/needs-investigation, category/umbraco-cms, category/umbraco-v10

#4083 Verified grid editor for v10
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Add-Value-Programmatically.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Configuring-The-Grid-Layout-Datatype.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Layout-Best-Practices.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Images/Grid-config.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Images/grid-settings-and-style.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Render-Grid-In-Template.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Settings-and-styles.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/What-Are-Grid-Layouts.md
Labels: category/umbraco-cms, category/umbraco-v10

#4089 Cleaned up product dependencies on cloud
  Umbraco-Cloud/Upgrades/Product-Dependencies/index.md
Labels: category/umbraco-cloud

#4091 Removed the Umbraco 9 reference
  Umbraco-Cloud/Set-Up/Working-Locally/index.md
Labels: category/umbraco-cloud

#4095 Added upgrade note for Forms 10.
  Add-ons/UmbracoForms/Installation/Version-Specific.md
Labels: category/umbraco-forms, category/umbraco-v10

#4057 Verified Managing Hostnames article for v10
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Security-Certificates/index.md
  Umbraco-Cloud/Set-Up/Manage-Hostnames/images/culture-and-hostnames-v10.png
  Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#4094 Added details of renaming git hook when renaming the project folder for a Cloud project.
  Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
Labels: category/umbraco-cloud, category/umbraco-deploy

#4099 v10: Version landing pages
  Add-ons/index.md
  Extending/index.md
  Fundamentals/Backoffice/index.md
  Fundamentals/Code/index.md
  Fundamentals/Data/index.md
  Fundamentals/Design/index.md
  Fundamentals/index.md
  Tutorials/index.md
  Umbraco-Cloud/index.md
Labels: category/umbraco-v10

#4097 v10: Cleanup some Cloud Articles
  Umbraco-Cloud/Troubleshooting/Deployments/Changes-Not-Being-Applied/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/Connection-Forcibly/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/Type-Not-Found/index.md
  Umbraco-Cloud/Troubleshooting/Deployments/index.md
  Umbraco-Cloud/Troubleshooting/troubleshooting-backoffice.md
  Umbraco-Cloud/Troubleshooting/troubleshooting-frontend.md
  Umbraco-Cloud/Troubleshooting/troubleshooting-portal.md
  Umbraco-Cloud/Troubleshooting/troubleshooting-siteperformance.md
Labels: category/umbraco-cloud

#4098 Renamed v10 articles
  Extending/Backoffice-UI-API-Documentation/index-v9.md
  Extending/Backoffice-UI-API-Documentation/index.md
  Extending/Key-Vault/index-v9.md
  Extending/Key-Vault/index.md
  Fundamentals/Code/Source-Control/index-v10.md
  Fundamentals/Code/Source-Control/index-v9.md
  Fundamentals/Code/Source-Control/index.md
  Fundamentals/Setup/Requirements/index-v9.md
  Fundamentals/Setup/Requirements/index.md
  Reference/API-Documentation/index-v9.md
  Reference/API-Documentation/index.md
  Reference/Configuration/ConnectionStringsSettings/index-v10.md
  Reference/Configuration/ConnectionStringsSettings/index-v9.md
  Reference/Configuration/ConnectionStringsSettings/index.md
  Reference/Configuration/GlobalSettings/index-v9.md
  Reference/Configuration/GlobalSettings/index.md
  Reference/Configuration/ImagingSettings/index-v9.md
  Reference/Configuration/ImagingSettings/index.md
  Tutorials/Members-Registration-And-Logins/index-v10.md
  Tutorials/Members-Registration-And-Logins/index-v9.md
  Tutorials/Members-Registration-And-Logins/index.md
Labels: category/umbraco-v10

#4082 Added article for v9 to v10 upgrade on Cloud
  Reference/Routing/IISRewriteRules/index.md
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/images/Nuget-Version-Install.png
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/images/Runtime-Settings.png
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/images/Solution-Explorer.png
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/images/Target-Framework.png
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/images/verify-v10-upgrade-locally.png
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#4101 Cloud updates
  Umbraco-Cloud/Security/index.md
  Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-Deploy-and-Courier-Upgrade.md
  Umbraco-Cloud/Upgrades/Manual-Upgrades/index.md
  Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
  Umbraco-Cloud/Upgrades/Product-Dependencies/index.md
  Umbraco-Cloud/Upgrades/index.md
Labels: category/umbraco-cloud

#4092 Remove forms folder added
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms, category/umbraco-v10

#4102 Documented prefer local db configuration
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
  Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
Labels: category/umbraco-deploy, category/umbraco-v10

#4104 Added link between CMS and Cloud upgrade guides for v10
  Fundamentals/Setup/Upgrading/version-specific.md
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
Labels: category/umbraco-cloud, category/umbraco-v10

#4031 Updated "Starter Kit" tutorial for v10
  Tutorials/Starter-kit/Index.md
  Tutorials/Starter-kit/Lessons/1-Customise-the-Starter-Kit/index.md
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/images/Blogpost-Document-Type-v10.png
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/images/property-settings-v10.png
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/index.md
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-2.md
  Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-3.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/index.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-1.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-2.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-3.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4.md
  Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/summary.md
  Tutorials/Starter-kit/Lessons/4-Ask-For-Help-and-Join-The-Community/index.md
  Tutorials/Starter-kit/Lessons/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4107 Do not use NText anymore, nvarchar(max)
  Extending/Database/index.md
Labels: category/code-example

#4112 Update ExcessiveHeaders.md
  Extending/Health-Check/Guides/ExcessiveHeaders.md
Labels: category/umbraco-cms

#4116 Update image and description for cloning a project.
  Umbraco-Cloud/Set-Up/Working-Locally/images/connect-my-machine.png
  Umbraco-Cloud/Set-Up/Working-Locally/index.md
Labels: category/umbraco-cloud

#4115 Update IContentFinder code samples
  Reference/Routing/Request-Pipeline/IContentFinder.md
Labels: category/umbraco-cms

#4121 Fixed typo
  Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Labels: category/umbraco-cloud

#4122 Added Note for clarity
  Tutorials/Creating-Tables-for-Umbraco-with-PetaPoco/index.md
Labels: category/umbraco-cms

#4125 Update sentence
  Reference/Configuration/index.md
Labels: category/umbraco-cms

#4126 Update blob version number in Cloud 9 to 10 guide
  Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
Labels: category/umbraco-cloud

#4123 Renamed Folder to fix URL
  Extending/UI-Library/images/Canvas_tab.png
  Extending/UI-Library/images/Docs_tab.png
  Extending/UI-Library/index.md
Labels: category/umbraco-cms

#4077 v10: Update articles with references to embedded resources
  Extending/Backoffice-Tours/index.md
  Extending/Language-Files/index.md
Labels: state/needs-investigation, category/umbraco-cms, category/umbraco-v10

#4132 Removed line about BootFailed.html file
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms

#4129 Updated the partial views with the new method signature
  Reference/Templating/Mvc/partial-views.md
Labels: category/umbraco-cms

#4128 Update if statement
  Tutorials/Creating-a-Property-Editor/part-2.md
Labels: category/umbraco-cms

#4133 Fix url to apidocs
  Extending/Embedded-Media-Provider/index.md
Labels: category/umbraco-cms

#4137 Added reference to Umbraco's dotnet new templates in the Abbreviated version
  Fundamentals/Setup/Install/visual-studio.md
Labels: category/umbraco-cms

#4139 Fix typo in timespan
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Labels: category/umbraco-deploy

#4135 Updated the article from v9 to v10
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-9/index.md
Labels: category/umbraco-cloud

#4140 Renamed Folders and some file clean-up
  Umbraco-Cloud/Upgrades/Migrating-from-7-to-8/index.md
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/images/upgrade-to-9_1.png
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-9/index.md
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/images/Nuget-Version-Install.png
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/images/Runtime-Settings.png
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/images/Solution-Explorer.png
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/images/Target-Framework.png
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/images/verify-v10-upgrade-locally.png
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
Labels: category/umbraco-cloud

#4144 Fix typos
  Extending/Key-Vault/index.md
Labels: category/umbraco-cms

#4146 Info about packages to update
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
Labels: category/umbraco-cloud

#4148 v9 - v10 Upgrade step improvements
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms

#4149 Fixed broken links in the Contribute article
  Contribute/Style-Guide/index.md
Labels: category/umbraco-cms

#4151 Removed duplicate UDA File mentions
  Umbraco-Cloud/Deployment/Deploy-Operations/Extract-schema-to-data-files/index.md
  Umbraco-Cloud/Set-Up/Power-Tools/Generating-UDA-files/index.md
Labels: category/umbraco-cloud

#4152 Remove umbracoSettingsFolder
  Reference/Configuration/umbracoSettings/index.md
Labels: category/umbraco-cms

#4154 Update ViewComponents-index.md
  Reference/Templating/Mvc/ViewComponents-index.md
Labels: category/umbraco-cms

#4141 Rewrite of the Sensitive Data article
  Reference/Security/images/member-property-options.png
  Reference/Security/sensitive-data.md
Labels: category/umbraco-cms

#4153 Updated Schema mismatch image and fixed grammatical errors
  Umbraco-Cloud/Troubleshooting/Deployments/Schema-Mismatches/images/schema-mismatch-on-transfer_v10.png
  Umbraco-Cloud/Troubleshooting/Deployments/Schema-Mismatches/index.md
Labels: category/umbraco-cloud

#4158 Cleanup duplicate schema mismatch article.
  Add-ons/Umbraco-Deploy/Troubleshooting/index.md
Labels: category/umbraco-deploy

#4160 Added a Note for v9 support
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
Labels: category/umbraco-cloud

#4159 Data types references
  Extending/Property-Editors/Tracking/images/data-types-references-v10.png
  Extending/Property-Editors/Tracking/images/document-references-v9.png
  Extending/Property-Editors/Tracking/images/media-references-v9.png
  Extending/Property-Editors/Tracking/index.md
  Fundamentals/Data/Data-Types/index.md
Labels: category/umbraco-cms
