Repository umbraco/UmbracoDocs, pull requests merged in 2022-02, with the labels that each got.

#3761 Updated the docs to match the new infrastructure
  Umbraco-Cloud/Frequently-Asked-Questions/index.md
  Umbraco-Cloud/Getting-Started/Umbraco-cloud-plans/index.md
  Umbraco-Cloud/Set-Up/External-Services/index.md
  Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
  Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/images/CMS-version-on-Umbraco-Cloud-project_1094x291.jpg
  Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/index.md
Labels: category/umbraco-cloud

#3771 Fix routing properties link
  Reference/Routing/Request-Pipeline/inbound-pipeline-v8.md
  Reference/Routing/routing-properties-v8.md
Labels: category/broken-link

#3773 Added new information for connecting to blob on cloud
  Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/images/blob.gif
  Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/index.md
  Umbraco-Cloud/release-notes/2022-01-31-ReleaseNotes.md
Labels: category/umbraco-cloud

#3787 Update version-specific.md
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-v9

#3704 Added docs for member transfer operations using Umbraco Deploy.
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Labels: category/pending-release, category/umbraco-deploy

#3763 Docs updates for the Forms 8.11/9.3 release.
  Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Developer/Security/images/user-group-permissions.png
  Add-ons/UmbracoForms/Developer/Security/images/user-start-folders.png
  Add-ons/UmbracoForms/Developer/Security/index.md
  Add-ons/UmbracoForms/Developer/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha3/index.md
  Add-ons/UmbracoForms/Editor/Viewing-and-Exporting-Entries/index.md
Labels: category/umbraco-forms, category/pending-release

#3785 Custom boot failed error page
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-v9

#3779 Add documentation for using IHtmlSanitizer
  Reference/Security/Serverside-sanitizing/index-v8.md
  Reference/Security/Serverside-sanitizing/index.md
Labels: category/pending-release, category/umbraco-cms, category/umbraco-v9

#3807 Added Import/export document type section
  Fundamentals/Data/Defining-content/images/import-document-type.png
  Fundamentals/Data/Defining-content/images/v8Screenshots/export-document-type.png
  Fundamentals/Data/Defining-content/index.md
Labels: category/umbraco-cms

#3808 Added necessary cookies information
  Reference/Security/Cookies/index.md
Labels: category/umbraco-cms, category/umbraco-v9

#3798 Updated settings for 8.18
  Reference/Config/umbracoSettings/index.md
Labels: category/pending-release

#3815 Added missing detail about configuration for Umbraco Deploy on-premises
  Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
Labels: category/umbraco-deploy
