Repository umbraco/UmbracoDocs, pull requests merged in 2022-11, with the labels that each got.

#4554 Fix typo, capitalize JSON
  Extending/Health-Check/Guides/DebugCompilationMode.md
  Extending/Health-Check/Guides/FixedApplicationUrl.md
  Extending/Health-Check/Guides/HttpsConfiguration.md
  Extending/Health-Check/Guides/NotificationEmail.md
  Extending/Health-Check/Guides/SMTP.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4461 Update outbound-pipeline.md
  Reference/Routing/Request-Pipeline/outbound-pipeline.md
Labels: category/umbraco-cms, hacktoberfest-accepted, dteam/review

#4511 Docs: make friendly
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
  Extending/Health-Check/Guides/HttpsConfiguration.md
  Extending/index-v8.md
  Fundamentals/Data/Creating-Media/default-media-types.md
  Fundamentals/Setup/Install/install-umbraco-with-vs-code.md
  Implementation/Unit-Testing/index-v8.md
  Reference/Configuration/WebRoutingSettings/index.md
  Reference/Events/CacheRefresher-Events.md
  Reference/Management/Services/ConsentService/Index-v7.md
  Reference/Management/Services/ConsentService/Index-v8.md
  Reference/Management/Services/ConsentService/Index.md
  Reference/Routing/Custom-Routes/index.md
  Reference/Templating/Modelsbuilder/Builder-Modes-v7.md
  Tutorials/Editors-Manual/Working-with-Content/Rich-Text-Editor/index-v7.md
  Umbraco-Cloud/Set-Up/Config-Transforms/index-v7.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4561 Restructured Getting started
  getting-started/README.md
  getting-started/creating-websites-with-umbraco.md
  getting-started/developing-websites-with-umbraco/README.md
  getting-started/developing-websites-with-umbraco/customizing-umbraco-sites.md
  getting-started/developing-websites-with-umbraco/extending-the-umbraco-backoffice.md
  getting-started/developing-websites-with-umbraco/images/Headless_Email_hero_780x405px.png
  getting-started/developing-websites-with-umbraco/images/Umbraco_Brand_Guidelines_2020_30_Illustrationbuilding.png
  getting-started/developing-websites-with-umbraco/images/corona_blogpost_05SoMe_768x432px.png
  getting-started/editing-websites-with-umbraco.md
  getting-started/hosting-an-umbraco-infrastructure.md
  getting-started/images/8_6_Email_hero_780x405px.png
  getting-started/images/Documentation_blogpost_styleguide_b.png
  getting-started/images/U_Docs.png
  getting-started/images/U_PRs.png
  getting-started/images/calendar_marked.png
  getting-started/images/cloud.png
  getting-started/images/code.png
  getting-started/images/contentstructure.png
  getting-started/images/editor.png
  getting-started/images/flexible_Email_hero_780x405px.png
  getting-started/images/globe.png
  getting-started/images/graph.png
  getting-started/images/support.png
  getting-started/images/tree.png
  getting-started/images/umbraco_8_2_A.png
  getting-started/images/umbraco_free_way_01.png
  getting-started/managing-an-umbraco-project.md
  getting-started/where-can-i-get-help.md
Labels: migration

#4562 Restructured CMS/implementation
  umbraco-cms/implementation/README.md
  umbraco-cms/implementation/composing.md
  umbraco-cms/implementation/controllers.md
  umbraco-cms/implementation/custom-routing/README.md
  umbraco-cms/implementation/custom-routing/signalR.md
  umbraco-cms/implementation/data-persistence.md
  umbraco-cms/implementation/default-routing/README.md
  umbraco-cms/implementation/default-routing/controller-selection.md
  umbraco-cms/implementation/default-routing/execute-request.md
  umbraco-cms/implementation/default-routing/inbound-pipeline.md
  umbraco-cms/implementation/integration-testing.md
  umbraco-cms/implementation/nullable-reference-types.md
  umbraco-cms/implementation/services/README.md
  umbraco-cms/implementation/services/circular-dependencies.md
  umbraco-cms/implementation/services/images/vs-di-constructor-generation-tip.gif
  umbraco-cms/implementation/unit-testing.md
Labels: migration

#4566 Restructure contribute
  Contribute/DocsTemplates/GenericTemplate.md
  Contribute/DocsTemplates/TutorialsTemplates.md
  Contribute/DocsTemplates/index.md
  contribute/README.md
  contribute/adding-metadata.md
  contribute/code-samples.md
  contribute/file-naming-conventions.md
  contribute/how-do-add-a-new-version.md
  contribute/images/PR-edit-this-page.png
  contribute/images/add-syntax-highlighting.png
  contribute/images/arm_with_u_logo-SMALL.png
  contribute/images/arm_with_u_logo.png
  contribute/images/c-trib-badge.png
  contribute/images/clone-your-fork.png
  contribute/images/codesnippet-sample.png
  contribute/images/edit-this-page.png
  contribute/images/example-of-fork.png
  contribute/images/extension.PNG
  contribute/images/fork-repository.png
  contribute/images/inline-sample.png
  contribute/images/new-issue.png
  contribute/images/pull-request.png
  contribute/images/report-issue.png
  contribute/images/snippet-with-syntaxhighlighting.png
  contribute/images/snippet-without-syntaxhighlighting.png
  contribute/images/submit-a-pull-request.png
  contribute/images/vale-output.PNG
  contribute/issues.md
  contribute/markdown-conventions.md
  contribute/pull-request.md
  contribute/style-guide.md
Labels: migration

#4577 Cleanup/implementation
  umbraco-cms/implementation/composing.md
  umbraco-cms/implementation/controllers.md
  umbraco-cms/implementation/custom-routing/README.md
  umbraco-cms/implementation/custom-routing/signalR.md
  umbraco-cms/implementation/data-persistence.md
  umbraco-cms/implementation/default-routing/controller-selection.md
  umbraco-cms/implementation/default-routing/execute-request.md
  umbraco-cms/implementation/default-routing/inbound-pipeline.md
  umbraco-cms/implementation/services/README.md
  umbraco-cms/implementation/unit-testing.md
Labels: migration

#4579 Cleanup cms/fundamentals/backoffice/property-editors article Part 1
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/block-grid-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/block-list-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/build-custom-view-for-blocks.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/label-property-configuration.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/checkBox-list.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/color-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/content-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-multiple-publish-keys.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-multiple.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-publishing-keys.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/add-value-programmatically.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/build-your-own-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/configuring-the-grid-layout-datatype.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/grid-editors.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/grid-layout-best-practices.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/render-grid-in-template.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/settings-and-styles.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/what-are-grid-layouts.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/configuration.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/rte-styles.md
Labels: category/umbraco-cms, migration

#4580 Cleanup property editor articles Part 2
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/date-time.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/date.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/decimal.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/email-address.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/eye-dropper-color-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/file-upload.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/image-cropper.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/label.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/listview.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/markdown-editor.md
Labels: category/umbraco-cms, migration

#4583 Cleanup property editor articles Final Part
  SUMMARY.md
  umbraco-cms/fundamentals/backoffice/property-editors/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/block-list-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/media-picker-3.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/media-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/member-group-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/member-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/multi-url-picker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/multinode-treepicker.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/multiple-textbox.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/nested-content.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/numeric.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/radiobutton-list.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/related-links.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/slider.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/tags.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/textarea.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/textbox.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/true-false.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/user-picker.md
Labels: category/umbraco-cms, migration

#4589 Cleanup Reference part3
  umbraco-cms/reference/angular/README.md
  umbraco-cms/reference/angular/directives/README.md
  umbraco-cms/reference/angular/services/README.md
  umbraco-cms/reference/cache/README.md
  umbraco-cms/reference/cache/iservermessenger.md
  umbraco-cms/reference/configuration/README.md
  umbraco-cms/reference/configuration/contentsettings.md
  umbraco-cms/reference/configuration/filesystemproviders.md
  umbraco-cms/reference/configuration/globalsettings.md
  umbraco-cms/reference/configuration/healthchecks.md
  umbraco-cms/reference/configuration/imagingsettings.md
  umbraco-cms/reference/configuration/loggingsettings.md
  umbraco-cms/reference/configuration/runtimeminificationsettings.md
  umbraco-cms/reference/configuration/runtimesettings.md
  umbraco-cms/reference/configuration/securitysettings.md
  umbraco-cms/reference/searching/examine/README.md
Labels: migration

#4590 cleaned up extending section
  umbraco-cms/extending/README.md
  umbraco-cms/extending/backoffice-search.md
  umbraco-cms/extending/backoffice-tours.md
  umbraco-cms/extending/content-apps.md
  umbraco-cms/extending/dashboards.md
  umbraco-cms/extending/database-v11.md
  umbraco-cms/extending/database.md
  umbraco-cms/extending/filesystemproviders/README.md
  umbraco-cms/extending/filesystemproviders/azure-blob-storage.md
  umbraco-cms/extending/health-check/README.md
  umbraco-cms/extending/health-check/guides/README.md
  umbraco-cms/extending/health-check/guides/excessiveheaders.md
  umbraco-cms/extending/health-check/guides/folderandfilepermissions.md
  umbraco-cms/extending/health-check/guides/stricttransportsecurityheader.md
  umbraco-cms/extending/key-vault.md
  umbraco-cms/extending/language-files.md
  umbraco-cms/extending/macro-parameter-editors.md
  umbraco-cms/extending/packages/README.md
  umbraco-cms/extending/packages/creating-a-package-v11.md
  umbraco-cms/extending/packages/creating-a-package.md
  umbraco-cms/extending/packages/installing-and-uninstalling-packages.md
  umbraco-cms/extending/packages/language-files-for-packages.md
  umbraco-cms/extending/packages/maintaining-packages.md
  umbraco-cms/extending/packages/packages-on-umbraco-cloud.md
  umbraco-cms/extending/packages/types-of-packages.md
  umbraco-cms/extending/packages/uploading-to-our.md
  umbraco-cms/extending/property-editors/README.md
  umbraco-cms/extending/property-editors/build-a-block-editor.md
  umbraco-cms/extending/property-editors/package-manifest.md
  umbraco-cms/extending/property-editors/property-actions.md
  umbraco-cms/extending/property-editors/property-value-converters.md
  umbraco-cms/extending/property-editors/tracking.md
  umbraco-cms/extending/section-trees/README.md
  umbraco-cms/extending/section-trees/searchable-trees.md
  umbraco-cms/extending/section-trees/sections.md
  umbraco-cms/extending/section-trees/trees/README.md
  umbraco-cms/extending/ui-library.md
Labels: migration

#4555 Improve readability - Fundamentals Data Content-Version-Cleanup
  Fundamentals/Data/Content-Version-Cleanup/index.md
Labels: hacktoberfest-accepted, category/styleguide, pending-platform-migration

#4556 Cleanup cloud portal article
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/images/Settings.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/images/change-profile-info.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index-v7.md
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md
Labels: category/umbraco-cloud, pending-platform-migration

#4557 Updated Project Settings article
  Umbraco-Cloud/Set-Up/Project-settings/images/Advanced-Settings.png
  Umbraco-Cloud/Set-Up/Project-settings/index.md
Labels: category/umbraco-cloud, pending-platform-migration

#4567 Fixes incorrect reference to Forms configuration key.
  Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Developer/Security/index.md
Labels: category/umbraco-forms, pending-platform-migration

#4578 Update .Url heading to match code sample
  Reference/Querying/IPublishedContent/Properties/index.md
Labels: category/umbraco-cms, pending-platform-migration

#4572 Added docs on grid cell value connectors.
  Add-ons/Umbraco-Deploy/Extending/index.md
Labels: category/umbraco-deploy, pending-platform-migration

#4588 Improve readability - Fundamentals Data Data-Types
  Fundamentals/Data/Data-Types/index.md
Labels: category/styleguide, pending-platform-migration

#4591 Fix casing for block grid components path
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Labels: category/umbraco-cms

#4593 Deploy cleanup
  umbraco-deploy/README.md
  umbraco-deploy/deploy-settings.md
  umbraco-deploy/deployment-workflow/README.md
  umbraco-deploy/deployment-workflow/content-transfer.md
  umbraco-deploy/deployment-workflow/deploying-changes.md
  umbraco-deploy/deployment-workflow/deploying-deletions.md
  umbraco-deploy/deployment-workflow/restoring-content/README.md
  umbraco-deploy/deployment-workflow/restoring-content/partial-restore.md
  umbraco-deploy/extending.md
  umbraco-deploy/get-started-with-deploy.md
  umbraco-deploy/installing-deploy/README.md
  umbraco-deploy/installing-deploy/cicd-pipeline/README.md
  umbraco-deploy/installing-deploy/cicd-pipeline/ci-cd-azure-dev-ops.md
  umbraco-deploy/installing-deploy/cicd-pipeline/ci-cd-github-actions.md
  umbraco-deploy/installing-deploy/existing-site.md
  umbraco-deploy/installing-deploy/install-configure.md
  umbraco-deploy/installing-deploy/new-site.md
  umbraco-deploy/troubleshooting.md
  umbraco-deploy/upgrades/README.md
  umbraco-deploy/upgrades/version-specific.md
Labels: category/umbraco-deploy, migration

#4595 added null check
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index-v8.md
Labels: category/umbraco-cms

#4594 Cleanup Forms section
  SUMMARY.md
  umbraco-forms/README.md
  umbraco-forms/developer/README.md
  umbraco-forms/developer/ajaxforms.md
  umbraco-forms/developer/blocklistfilters.md
  umbraco-forms/developer/configuration/README.md
  umbraco-forms/developer/configuration/type-details.md
  umbraco-forms/developer/contentapps.md
  umbraco-forms/developer/custom-markup.md
  umbraco-forms/developer/email-templates.md
  umbraco-forms/developer/extending/README.md
  umbraco-forms/developer/extending/adding-a-exporttype.md
  umbraco-forms/developer/extending/adding-a-fieldtype.md
  umbraco-forms/developer/extending/adding-a-magic-string-format-function.md
  umbraco-forms/developer/extending/adding-a-prevaluesourcetype.md
  umbraco-forms/developer/extending/adding-a-type.md
  umbraco-forms/developer/extending/adding-a-workflowtype.md
  umbraco-forms/developer/extending/adding-an-event-handler.md
  umbraco-forms/developer/extending/customize-default-workflows.md
  umbraco-forms/developer/field-types.md
  umbraco-forms/developer/forms-in-the-database.md
  umbraco-forms/developer/healthchecks/README.md
  umbraco-forms/developer/ifilesystem.md
  umbraco-forms/developer/iprevaluetextfilestorage.md
  umbraco-forms/developer/localization.md
  umbraco-forms/developer/magic-strings.md
  umbraco-forms/developer/prepping-frontend.md
  umbraco-forms/developer/rendering-scripts.md
  umbraco-forms/developer/security.md
  umbraco-forms/developer/themes.md
  umbraco-forms/developer/working-with-data.md
  umbraco-forms/editor/README.md
  umbraco-forms/editor/attaching-workflows/README.md
  umbraco-forms/editor/attaching-workflows/workflow-types.md
  umbraco-forms/editor/creating-a-form/README.md
  umbraco-forms/editor/creating-a-form/conditional-logic.md
  umbraco-forms/editor/creating-a-form/fieldtypes/README.md
  umbraco-forms/editor/creating-a-form/fieldtypes/date.md
  umbraco-forms/editor/creating-a-form/fieldtypes/fileupload.md
  umbraco-forms/editor/creating-a-form/fieldtypes/recaptcha2.md
  umbraco-forms/editor/creating-a-form/fieldtypes/recaptcha3.md
  umbraco-forms/editor/creating-a-form/form-settings.md
  umbraco-forms/editor/defining-and-attaching-prevaluesources/README.md
  umbraco-forms/editor/defining-and-attaching-prevaluesources/prevalue-source-types.md
  umbraco-forms/editor/viewing-and-exporting-entries.md
  umbraco-forms/installation/README.md
  umbraco-forms/installation/install.md
  umbraco-forms/installation/manualupgrade.md
  umbraco-forms/installation/upgrade.md
  umbraco-forms/installation/version-specific.md
Labels: category/umbraco-forms, migration

#4596 Heartcore cleanup
  umbraco-heartcore/README.md
  umbraco-heartcore/api-documentation/README.md
  umbraco-heartcore/api-documentation/content-delivery/README.md
  umbraco-heartcore/api-documentation/content-management/README.md
  umbraco-heartcore/api-documentation/content-management/content/README.md
  umbraco-heartcore/api-documentation/content-management/forms.md
  umbraco-heartcore/api-documentation/content-management/language.md
  umbraco-heartcore/api-documentation/graphql/README.md
  umbraco-heartcore/api-documentation/graphql/filtering-and-ordering.md
  umbraco-heartcore/api-documentation/graphql/property-editors.md
  umbraco-heartcore/api-documentation/graphql/schema-generation.md
  umbraco-heartcore/api-documentation/redirect.md
  umbraco-heartcore/backoffice/grid-editors.md
  umbraco-heartcore/client-libraries/README.md
  umbraco-heartcore/client-libraries/dot-net-console.md
  umbraco-heartcore/client-libraries/dot-net-core/README.md
  umbraco-heartcore/client-libraries/dot-net-core/mvc-samples.md
  umbraco-heartcore/client-libraries/node-js.md
  umbraco-heartcore/getting-started/api-browser.md
  umbraco-heartcore/getting-started/creating-a-heartcore-project.md
  umbraco-heartcore/getting-started/deployment-workflow/content-transfer.md
  umbraco-heartcore/getting-started/environments.md
  umbraco-heartcore/getting-started/graphql-playground.md
  umbraco-heartcore/getting-started/preview.md
  umbraco-heartcore/getting-started/the-cloud-portal.md
  umbraco-heartcore/getting-started/using-the-forms-api.md
  umbraco-heartcore/sso-guide.md
  umbraco-heartcore/tutorials/README.md
  umbraco-heartcore/tutorials/creating-a-custom-grid-editor.md
  umbraco-heartcore/tutorials/querying-with-graphql.md
  umbraco-heartcore/versions-and-updates.md
Labels: migration

#4599 Removed deprecated video from docs
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index-v8.md
Labels: category/umbraco-cloud

#4553 Forms-PreValueSourceType - Additional example added
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Prevaluesourcetype.md
Labels: hacktoberfest-accepted

#4559 Forms 10.2 post RC docs updates
  Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
Labels: category/umbraco-forms, category/pending-release, pending-platform-migration

#4601 Improve readability - Fundamentals Code Creating-Forms
  Fundamentals/Code/Creating-Forms/index.md
Labels: category/styleguide

#4603 Reference script instead of html view
  Extending/Property-Editors/Package-Manifest/index.md
Labels: category/umbraco-cms

#4604 Add merged PRs to migrated docs
  umbraco-cloud/getting-started/the-umbraco-cloud-portal/README.md
  umbraco-cloud/getting-started/the-umbraco-cloud-portal/images/Settings.png
  umbraco-cloud/getting-started/the-umbraco-cloud-portal/images/change-profile-info-new.png
  umbraco-cloud/getting-started/the-umbraco-cloud-portal/images/change-profile-info.png
  umbraco-cloud/set-up/images/Advanced-Settings-new.png
  umbraco-cloud/set-up/images/Advanced-Settings.png
  umbraco-cloud/set-up/project-settings.md
  umbraco-cloud/troubleshooting/deployments/README.md
  umbraco-cms/extending/property-editors/package-manifest.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/multinode-treepicker.md
  umbraco-cms/fundamentals/code/creating-forms.md
  umbraco-cms/fundamentals/data/content-version-cleanup.md
  umbraco-cms/fundamentals/data/data-types/README.md
  umbraco-cms/fundamentals/setup/install/unattended-install.md
  umbraco-cms/reference/querying/ipublishedcontent/properties.md
  umbraco-forms/developer/configuration/README.md
  umbraco-forms/developer/extending/adding-a-prevaluesourcetype.md
  umbraco-forms/developer/magic-strings.md
  umbraco-forms/developer/security.md
Labels: migration

#4605 Add #4572 to migrated docs
  umbraco-deploy/extending.md
Labels: migration

#4540 Adds CRUD example to Database-page (could fix #3617)
  Extending/Database/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, dteam/review

#4608 Update and restructure Contrib docs
  .github/README.md
  SUMMARY.md
  contribute/README.md
  contribute/adding-metadata.md
  contribute/code-samples.md
  contribute/file-naming-conventions.md
  contribute/how-do-add-a-new-version.md
  contribute/images/PR-edit-this-page.png
  contribute/images/arm_with_u_logo.png
  contribute/images/contribute.png
  contribute/images/edit-this-page.png
  contribute/images/fork-repository-new.png
  contribute/images/fork-repository.png
  contribute/images/gb-edit-on-github.png
  contribute/images/new-issue-new.png
  contribute/images/new-issue.png
  contribute/images/rate-article.png
  contribute/images/sync-fork.png
  contribute/issues.md
  contribute/markdown-conventions.md
  contribute/pull-request.md
  contribute/structure.md
  documentation-and-versions.md
Labels: migration

#4612 Improve readability - Fundamentals
  Fundamentals/index.md
Labels: category/styleguide

#4614 New default upgrade
  .gitbook.yaml
  SUMMARY.md
  umbraco-cms/fundamentals/setup/server-setup/load-balancing/README.md
  umbraco-cms/fundamentals/setup/upgrading/README.md
  umbraco-cms/fundamentals/setup/upgrading/general.md
  umbraco-cms/fundamentals/setup/upgrading/version-specific.md
Labels: category/umbraco-cms, release/11.0.0

#4600 Cloud release notes 2022-11-07
  Umbraco-Cloud/Release-Notes/2022-11-07-ReleaseNotes.md
  Umbraco-Cloud/Release-Notes/images/DedicatedStarter.png
  Umbraco-Cloud/Release-Notes/images/ProjectsDashboardHoverEnvironment.gif
  Umbraco-Cloud/Release-Notes/index.md
Labels: category/umbraco-cloud

#4619 Improve readability - Fundamentals Backoffice Property Editors
  Fundamentals/Backoffice/Property-Editors/index.md
Labels: category/styleguide

#4620 Verified for v11
  umbraco-forms/installation/manualupgrade.md
Labels: category/umbraco-forms

#4622 Add Cloud Release notes to migrated docs
  umbraco-cloud/release-notes/2022-11-07-releasenotes.md
  umbraco-cloud/release-notes/README.md
  umbraco-cloud/release-notes/images/DedicatedStarter.png
  umbraco-cloud/release-notes/images/ProjectsDashboardHoverEnvironment.gif
Labels: migration

#4525 Update Requirements article for Umbraco 11
  Fundamentals/Setup/Requirements/index-v11.md
Labels: category/umbraco-cms, dteam/review, release/11.0.0

#4602 Upgrade globaljson
  Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
  Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
Labels: category/umbraco-cloud

#4610 Changes and improvements for the Block Grid Editor documentation
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/build-custom-view-for-blocks.md
Labels: category/pending-release, category/umbraco-cms, release/11.0.0

#4546 Documented Deploy's SourceDeployBatchSize setting.
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Labels: category/pending-release, category/umbraco-deploy

#4617 Added info about custom IContentLastChanceFinder
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms

#4609 Add #4540 to migrated docs
  umbraco-cms/extending/database.md
Labels: migration

#4629 New requirements and new 11 specific config
  .github/styles/UmbracoDocs/Acronyms.yml
  umbraco-cms/fundamentals/setup/requirements.md
  umbraco-cms/reference/configuration/installdefaultdatasettings.md
Labels: migration

#4628 Add merged PRs to migrated Docs
  umbraco-cloud/upgrades/migrating-from-8-10.md
  umbraco-cloud/upgrades/upgrading-from-9-10.md
  umbraco-cms/fundamentals/backoffice/logviewer.md
  umbraco-cms/reference/configuration/installdefaultdatasettings.md
  umbraco-cms/tutorials/custom-error-page.md
  umbraco-deploy/deploy-settings.md
  umbraco-heartcore/tutorials/creating-a-custom-grid-editor.md
Labels: migration

#4631 Improve readability - Fundamentals Code Debugging
  Fundamentals/Code/Debugging/index.md
Labels: category/styleguide

#4632 Add note about git branches when contributing
  contribute/pull-request.md
Labels: migration

#4633 Move gif from Config section to Scaling blocks
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Labels: category/umbraco-cms, release/11.0.0

#4637 Add merged PRs to migrated docs
  umbraco-cms/fundamentals/code/debugging/README.md
  umbraco-heartcore/api-documentation/redirect.md
Labels: migration

#4636 Add new Block Grid Editor editions to migrated docs
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/build-custom-view-for-blocks.md
Labels: migration

#4638 Add relevant PRs to 11 Docs
  contribute/pull-request.md
  umbraco-cloud/upgrades/migrating-from-8-10.md
  umbraco-cloud/upgrades/upgrading-from-9-10.md
  umbraco-cms/fundamentals/backoffice/logviewer.md
  umbraco-cms/fundamentals/code/debugging/README.md
  umbraco-cms/tutorials/custom-error-page.md
  umbraco-deploy/deploy-settings.md
  umbraco-heartcore/api-documentation/redirect.md
  umbraco-heartcore/tutorials/creating-a-custom-grid-editor.md
Labels: migration

#4642 Link to Azure Key Vault page added to Web App page
  Fundamentals/Setup/Server-Setup/azure-web-apps.md
Labels: category/umbraco-cms

#4645 Correct user language file path
  Extending/Dashboards/index.md
Labels: category/umbraco-cms

#4647 Making sure the code sample matches with the Samples repo
  Tutorials/Members-Registration-And-Logins/index.md
Labels: category/umbraco-cms

#4649 Update documentation to use private cache instead of shared
  Reference/Configuration/ConnectionStringsSettings/index.md
Labels: category/umbraco-cms

#4648 Add section on runtime minification
  Extending/Macro-Parameter-Editors/index.md
Labels: category/umbraco-cms

#4654 Update Builder-Modes.md
  Reference/Templating/Modelsbuilder/Builder-Modes.md
Labels: category/umbraco-cms

#4655 Add merged PRs to GitBook
  SUMMARY.md
  umbraco-cms/extending/dashboards.md
  umbraco-cms/extending/macro-parameter-editors.md
  umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
  umbraco-cms/reference/configuration/connectionstringssettings.md
  umbraco-cms/reference/templating/modelsbuilder/builder-modes.md
  umbraco-deploy/installing-deploy/README.md
  umbraco-deploy/installing-deploy/streamlining-local-development.md
Labels: migration

#4658 Add merged PR to migrated to (11)
  SUMMARY.md
  umbraco-cms/extending/dashboards.md
  umbraco-cms/extending/macro-parameter-editors.md
  umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
  umbraco-cms/reference/configuration/connectionstringssettings.md
  umbraco-cms/reference/templating/modelsbuilder/builder-modes.md
  umbraco-deploy/installing-deploy/README.md
  umbraco-deploy/installing-deploy/streamlining-local-development.md
Labels: migration

#4656 Update Content setting article for GitBook
  umbraco-cms/reference/configuration/contentsettings.md
Labels: migration

#4659 Update content settings article
  umbraco-cms/reference/configuration/contentsettings.md
Labels: migration

#4652 Fixing broken references in the cloud section
  umbraco-cloud/databases/cloud-database.md
  umbraco-cloud/deployment/restoring-content/README.md
  umbraco-cloud/getting-started/README.md
  umbraco-cloud/getting-started/the-umbraco-cloud-portal/README.md
  umbraco-cloud/set-up/power-tools/README.md
  umbraco-cloud/set-up/project-settings/application-settings.md
  umbraco-cloud/troubleshooting/deployments/path-too-long-exception.md
Labels: category/umbraco-cloud

#4660 Update working-locally.md
  umbraco-cloud/set-up/working-locally.md
Labels: category/umbraco-cloud

#4661 Update index.md
  Umbraco-Cloud/Set-Up/Working-Locally/index.md
Labels: category/umbraco-cloud

#4616 Example of how to create async RenderController
  Reference/Routing/Custom-Controllers/index.md
Labels: category/umbraco-cms, dteam/review

#4618 Warning about appsettings and IContentLastChanceFinder
  Reference/Routing/Request-Pipeline/IContentFinder.md
Labels: category/umbraco-cms, dteam/review

#4663 Added Content Management Api documentation for the Heartcore client library
  Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/Content-Management-Sample/index.md
  Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/index.md
Labels: category/umbraco-heartcore

#4667 Fix broken references in the Getting Started section including root
  getting-started/developing-websites-with-umbraco/README.md
  getting-started/developing-websites-with-umbraco/customizing-umbraco-sites.md
  getting-started/developing-websites-with-umbraco/extending-the-umbraco-backoffice.md
  getting-started/hosting-an-umbraco-infrastructure.md
  other-resources/the-licensing-model.md
Labels: migration

#4653 Improve readability - Fundamentals Setup Server-Setup
  Fundamentals/Setup/Server-Setup/index.md
Labels: category/styleguide

#4626 Update Rich text editor docs for 11
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/inline-mode-new.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-Formats.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-content-11.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-content.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-mode-classic-11.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-mode-classic.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-mode-distractionfree.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/rte-styles.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/toolbar-full-11.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/images/toolbar-full.png
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-styles.md
  umbraco-cms/fundamentals/setup/upgrading/version-specific/umbraco11-breaking-changes.md
  umbraco-cms/reference/configuration/richtexteditorsettings.md
Labels: category/umbraco-cms, release/11.0.0

#4670 added null checker for single item mode
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v8.md
Labels: category/umbraco-cms

#4668 Fix broken refs in the Implementation section
  umbraco-cms/implementation/composing.md
  umbraco-cms/implementation/custom-routing/README.md
  umbraco-cms/implementation/custom-routing/signalR.md
  umbraco-cms/implementation/data-persistence.md
  umbraco-cms/implementation/default-routing/README.md
  umbraco-cms/implementation/default-routing/controller-selection.md
  umbraco-cms/implementation/default-routing/inbound-pipeline.md
Labels: migration

#4674 Another Nested Content nullchecker for V9/10 docs
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Labels: category/umbraco-cms

#4677 Fix broken references in REference secion
  umbraco-cms/reference/angular/README.md
  umbraco-cms/reference/angular/services/eventsservice/README.md
  umbraco-cms/reference/cache/examples/tags.md
  umbraco-cms/reference/cache/updating-cache.md
  umbraco-cms/reference/common-pitfalls.md
  umbraco-cms/reference/configuration/keepalivesettings.md
  umbraco-cms/reference/configuration/maximumuploadsizesettings.md
  umbraco-cms/reference/management/README.md
  umbraco-cms/reference/management/models/README.md
  umbraco-cms/reference/management/services/README.md
  umbraco-cms/reference/notifications/contentservice-notifications.md
  umbraco-cms/reference/notifications/contentypeservice-notifications.md
  umbraco-cms/reference/notifications/datatypeservice-notifications.md
  umbraco-cms/reference/notifications/mediatypeservice-notifications.md
  umbraco-cms/reference/notifications/memberservice-notifications.md
  umbraco-cms/reference/notifications/membertypeservice-notifications.md
  umbraco-cms/reference/querying/ipublishedcontent/collections.md
  umbraco-cms/reference/querying/ipublishedcontent/ishelpers.md
  umbraco-cms/reference/querying/ipublishedcontent/properties.md
  umbraco-cms/reference/routing/authorized.md
  umbraco-cms/reference/routing/custom-controllers.md
  umbraco-cms/reference/routing/custom-routes.md
  umbraco-cms/reference/routing/iisrewriterules.md
  umbraco-cms/reference/routing/request-pipeline/find-publishedcontent-and-template.md
  umbraco-cms/reference/routing/request-pipeline/outbound-pipeline.md
  umbraco-cms/reference/routing/routing-properties.md
  umbraco-cms/reference/routing/umbraco-api-controllers/authorization.md
  umbraco-cms/reference/routing/umbraco-api-controllers/routing.md
  umbraco-cms/reference/scheduling.md
  umbraco-cms/reference/searching/examine/quick-start.md
  umbraco-cms/reference/security/README.md
  umbraco-cms/reference/security/auto-linking.md
  umbraco-cms/reference/security/custom-password-check.md
  umbraco-cms/reference/security/external-login-providers.md
  umbraco-cms/reference/security/password-reset.md
  umbraco-cms/reference/security/security-settings.md
  umbraco-cms/reference/templating/macros/README.md
  umbraco-cms/reference/templating/modelsbuilder/README.md
  umbraco-cms/reference/templating/mvc/README.md
  umbraco-cms/reference/templating/mvc/viewcomponents.md
  umbraco-cms/reference/templating/mvc/views.md
  umbraco-cms/reference/using-ioc.md
Labels: migration

#4678 Fix links
  .gitbook.yaml
  umbraco-cms/fundamentals/code/umbraco-services.md
  umbraco-cms/implementation/data-persistence.md
  umbraco-cms/implementation/services/README.md
Labels: migration

#4680 Broken refs
  getting-started/developing-websites-with-umbraco/README.md
  getting-started/developing-websites-with-umbraco/customizing-umbraco-sites.md
  getting-started/developing-websites-with-umbraco/extending-the-umbraco-backoffice.md
  getting-started/hosting-an-umbraco-infrastructure.md
  other-resources/the-licensing-model.md
  umbraco-cloud/set-up/working-locally.md
  umbraco-cms/implementation/composing.md
  umbraco-cms/implementation/custom-routing/README.md
  umbraco-cms/implementation/custom-routing/signalR.md
  umbraco-cms/implementation/data-persistence.md
  umbraco-cms/implementation/default-routing/README.md
  umbraco-cms/implementation/default-routing/controller-selection.md
  umbraco-cms/implementation/default-routing/inbound-pipeline.md
  umbraco-cms/reference/angular/README.md
  umbraco-cms/reference/angular/services/eventsservice/README.md
  umbraco-cms/reference/cache/updating-cache.md
  umbraco-cms/reference/common-pitfalls.md
  umbraco-cms/reference/configuration/keepalivesettings.md
  umbraco-cms/reference/configuration/maximumuploadsizesettings.md
  umbraco-cms/reference/management/README.md
  umbraco-cms/reference/management/models/README.md
  umbraco-cms/reference/management/services/README.md
  umbraco-cms/reference/notifications/contentservice-notifications.md
  umbraco-cms/reference/notifications/contentypeservice-notifications.md
  umbraco-cms/reference/notifications/datatypeservice-notifications.md
  umbraco-cms/reference/notifications/mediatypeservice-notifications.md
  umbraco-cms/reference/notifications/memberservice-notifications.md
  umbraco-cms/reference/notifications/membertypeservice-notifications.md
  umbraco-cms/reference/querying/ipublishedcontent/collections.md
  umbraco-cms/reference/querying/ipublishedcontent/ishelpers.md
  umbraco-cms/reference/querying/ipublishedcontent/properties.md
  umbraco-cms/reference/routing/authorized.md
  umbraco-cms/reference/routing/custom-controllers.md
  umbraco-cms/reference/routing/custom-routes.md
  umbraco-cms/reference/routing/iisrewriterules.md
  umbraco-cms/reference/routing/request-pipeline/find-publishedcontent-and-template.md
  umbraco-cms/reference/routing/request-pipeline/outbound-pipeline.md
  umbraco-cms/reference/routing/routing-properties.md
  umbraco-cms/reference/routing/umbraco-api-controllers/authorization.md
  umbraco-cms/reference/routing/umbraco-api-controllers/routing.md
  umbraco-cms/reference/scheduling.md
  umbraco-cms/reference/searching/examine/quick-start.md
  umbraco-cms/reference/security/README.md
  umbraco-cms/reference/security/auto-linking.md
  umbraco-cms/reference/security/custom-password-check.md
  umbraco-cms/reference/security/external-login-providers.md
  umbraco-cms/reference/security/password-reset.md
  umbraco-cms/reference/security/security-settings.md
  umbraco-cms/reference/templating/modelsbuilder/README.md
  umbraco-cms/reference/templating/mvc/README.md
  umbraco-cms/reference/templating/mvc/viewcomponents.md
  umbraco-cms/reference/templating/mvc/views.md
  umbraco-cms/reference/using-ioc.md
Labels: migration

#4684 Add merged PRs to migrated docs
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/nested-content.md
  umbraco-cms/fundamentals/setup/server-setup/README.md
  umbraco-cms/reference/routing/custom-controllers.md
Labels: migration

#4685 Fix API links in v10 Docs
  umbraco-cms/extending/dashboards.md
  umbraco-cms/extending/packages/language-files-for-packages.md
  umbraco-cms/extending/packages/packages-on-umbraco-cloud.md
  umbraco-cms/extending/property-editors/build-a-block-editor.md
  umbraco-cms/extending/property-editors/declaring-your-property-editor.md
  umbraco-cms/extending/section-trees/trees/README.md
  umbraco-cms/implementation/default-routing/inbound-pipeline.md
  umbraco-cms/implementation/unit-testing.md
  umbraco-cms/reference/angular/README.md
  umbraco-cms/reference/angular/directives/umbloadindicator.md
  umbraco-cms/reference/angular/directives/umbproperty.md
  umbraco-cms/reference/cache/README.md
  umbraco-cms/reference/management/services-reference/auditservice.md
  umbraco-cms/reference/management/services-reference/consentservice.md
  umbraco-cms/reference/management/services-reference/contentservice/README.md
  umbraco-cms/reference/management/services-reference/contenttypeservice/README.md
  umbraco-cms/reference/management/services-reference/datatypeservice.md
  umbraco-cms/reference/management/services-reference/entityservice.md
  umbraco-cms/reference/management/services-reference/fileservice.md
  umbraco-cms/reference/management/services-reference/localizationservice/README.md
  umbraco-cms/reference/management/services-reference/localizationservice/retrieving-languages.md
  umbraco-cms/reference/management/services-reference/macroservice.md
  umbraco-cms/reference/management/services-reference/mediaservice.md
  umbraco-cms/reference/management/services-reference/membergroupservice.md
  umbraco-cms/reference/querying/imembermanager.md
  umbraco-cms/reference/querying/udi-identifiers.md
  umbraco-cms/reference/security/backofficeusermanager-and-notifications.md
Labels: migration

#4688 Removed broken link as it's EOL in 2015...
  Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication.md
Labels: category/umbraco-cms

#4545 Further documentation updates for Deploy 11
  Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
Labels: category/pending-release, category/umbraco-deploy

#4687 Update landing pages
  umbraco-cloud/getting-started/README.md
  umbraco-cms/README.md
  umbraco-deploy/README.md
  umbraco-deploy/get-started-with-deploy.md
  umbraco-forms/README.md
  umbraco-heartcore/umbraco-heartcore/README.md
Labels: migration

#4681 Docs updates for Forms 10.2.1
  Add-ons/UmbracoForms/Developer/AjaxForms/index.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
Labels: category/umbraco-forms, category/pending-release

#4691 Improve readability - Fundamentals Design Partial-View-Macro-Files
  Fundamentals/Design/Partial-View-Macro-Files/index.md
Labels: category/styleguide

#4672 Add an intro to the RTE appSettings config
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
Labels: category/umbraco-cms

#4543 Further documentation updates for Forms 11
  Add-ons/UmbracoForms/Installation/Version-Specific.md
Labels: category/umbraco-forms, category/pending-release

#4695 Updated video link
  Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
Labels: category/umbraco-cloud

#4696 Add merged PRs as of November 29th
  umbraco-cms/fundamentals/design/partial-view-macro-files.md
  umbraco-cms/reference/querying/imembermanager.md
  umbraco-deploy/upgrades/version-specific.md
  umbraco-forms/developer/ajaxforms.md
  umbraco-forms/developer/configuration/README.md
  umbraco-forms/installation/version-specific.md
Labels: migration

#4697 Add merged PRs as of November 29 (Umbraco 11)
  umbraco-cloud/getting-started/README.md
  umbraco-cms/README.md
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
  umbraco-cms/fundamentals/design/partial-view-macro-files.md
  umbraco-cms/reference/querying/imembermanager.md
  umbraco-deploy/README.md
  umbraco-deploy/get-started-with-deploy.md
  umbraco-deploy/upgrades/version-specific.md
  umbraco-forms/README.md
  umbraco-forms/developer/ajaxforms.md
  umbraco-forms/developer/configuration/README.md
  umbraco-forms/installation/version-specific.md
  umbraco-heartcore/umbraco-heartcore/README.md
Labels: migration

#4693 Update licensing.md
  umbraco-workflow/licensing.md
Labels: category/umbraco-plumber, release/11.0.0

#4675 Adding crops directly into templates
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index-v8.md
Labels: category/umbraco-cloud

#4698 Fix scroll bar in RTE config article
  umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
Labels: migration

#4694 Update and rename events.md to notifications.md
  umbraco-workflow/events.md
  umbraco-workflow/notifications.md
Labels: category/umbraco-plumber, release/11.0.0
