Repository umbraco/UmbracoDocs, pull requests merged in 2022-10, with the labels that each got.

#4421 Delete CrossSiteScriptingProtection.md
  Extending/Health-Check/Guides/CrossSiteScriptingProtection.md
Labels: category/umbraco-cms

#4373 Licensing update for Plumber
  Add-ons/Umbraco-Plumber/Licensing/index.md
Labels: category/umbraco-plumber

#4417 Updated the cloud portal article with the new dashboard
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/images/Umbraco-cloud-dashboard.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/images/add-group.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/images/edit-group.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md
  Umbraco-Cloud/Getting-Started/images/create-project.png
  Umbraco-Cloud/Getting-Started/index.md
  Umbraco-Heartcore/Getting-Started-Cloud/The-Cloud-Portal/images/Heartcore-dashboard.png
  Umbraco-Heartcore/Getting-Started-Cloud/The-Cloud-Portal/index.md
Labels: category/umbraco-cloud, category/pending-release

#4422 Additional considerations in Production
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms, hacktoberfest/contrib-2022

#4427 Update Azure Load Balancing Maindom description
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4430 the instead of that
  Umbraco-Cloud/Upgrades/index.md
Labels: category/umbraco-cloud

#4414 Clarifying name of Class Library
  Umbraco-Cloud/Set-Up/Working-Locally/index.md
Labels: category/umbraco-cloud

#4407 Fixed a couple of layout and detail issues in Deploy's extending for custom entities documentation.
  Add-ons/Umbraco-Deploy/Extending/index-v8.md
  Add-ons/Umbraco-Deploy/Extending/index.md
Labels: category/umbraco-deploy, dteam/review

#4428 Created guide to migrate users to Umbraco Cloud
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbraco-Cloud/index.md
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Labels: category/umbraco-cloud

#4431 Update UI Library article for 10.3 release
  Extending/UI-Library/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, release/10.3.0, hacktoberfest/contrib-2022

#4398 Block Grid Docs
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_AddContent.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_AddContentInline.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_Areas.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_AreasConfiguration.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_BlockPicker.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_BlockPicker_exsetup.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_Configuration.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_DataType_Blocks.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockGridEditor_DeleteContent.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_AddContent.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_AddContentInline.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_BlockPicker.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_BlockPicker_simplesetup.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_DataType.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_DataType_Blocks.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_EditingOverlay.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/BlockListEditor_InlineEditing.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/Install-Sample-Configuration.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/Resizing-Blocks.gif
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/images/Sorting_BlockGrid_Blocks.gif
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_AddContent.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_AddContentInline.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_BlockPicker.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_BlockPicker_simplesetup.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_DataType.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_DataType_Blocks.png
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_EditingOverlay.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/images/BlockListEditor_InlineEditing.jpg
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index-v8.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/build-custom-view-for-blocks.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
Labels: category/umbraco-cms, release/10.3.0

#4432 Fixed quite some vale and markdown issues
  Add-ons/Umbraco-Deploy/Extending/index.md
Labels: hacktoberfest-accepted, category/umbraco-deploy, hacktoberfest/contrib-2022

#4436 SearchService codes are matching with Samples repo
  Reference/Querying/IPublishedContentQuery/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4435 Updated the Custom Indexing code to match to Samples repo
  Reference/Searching/Examine/Indexing/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4441 Macro Parameter Editors has a broken link
  Extending/Macro-Parameter-Editors/index-v8.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4443 Explain imanifest filters
  Extending/Property-Editors/Package-Manifest/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4442 Added element type section
  .github/styles/UmbracoDocs/Acronyms.yml
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index-v8.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index.md
  Fundamentals/Data/Defining-content/images/Element-Type.png
  Fundamentals/Data/Defining-content/index-v8.md
  Fundamentals/Data/Defining-content/index.md
Labels: category/umbraco-cms

#4448 Add" javascript -> JavaScript" rule and "azure -> Azure" rule
  .github/styles/UmbracoDocs/Brands.yml
  .github/styles/UmbracoDocs/Names.yml
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
  Extending/Section-Trees/Trees/index-v7.md
  Extending/Section-Trees/Trees/index-v8.md
  Extending/Section-Trees/Trees/index.md
  Fundamentals/Design/Stylesheets-Javascript/index-v7.md
  Fundamentals/Design/Stylesheets-Javascript/index.md
  Implementation/Custom-Routing/signalR.md
  Reference/Configuration-for-Umbraco-7-and-8/webconfig/index-v7.md
  Reference/Configuration-for-Umbraco-7-and-8/webconfig/index.md
  Reference/Routing/Surface-Controllers/index.md
  Tutorials/Creating-a-Custom-Dashboard/index-v7.md
  Umbraco-Cloud/Release-Notes/2022-05-23-ReleaseNotes.md
  Umbraco-Heartcore/Backoffice/Grid-Editors/index.md
  Umbraco-Heartcore/Getting-Started-Cloud/Using-The-Forms-API/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4445 Update about basic auth for Cloud version 10 projects
  Umbraco-Cloud/Security/index.md
Labels: category/umbraco-cloud

#4450 Some readability improvements
  Getting-Started/Developing-websites-with-Umbraco/Customizing-Umbraco-sites/index.md
  Implementation/Composing/index-v8.md
  Implementation/Composing/index.md
  Implementation/Data-Persistence/index-v8.md
  Implementation/Default-Routing/Inbound-Pipeline/index.md
  Implementation/Services/index-v8.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4452 Readability on Where can I get help.
  Getting-Started/Where-can-I-get-help/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4454 Clarify how block grid output is constructed by built-in views
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4455 Update block grid docs
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4446 Notifications matching to the Samples site
  Reference/Notifications/ContentService-Notifications/index.md
  Reference/Notifications/Creating-And-Publishing-Notifications/index-v9.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4457 Add AJAX and XSLT to the acronym exception lists
  .github/styles/UmbracoDocs/Acronyms.yml
Labels: category/styleguide

#4438 Clarified the requirements
  Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4458 added YAML to the acronymes
  .github/styles/UmbracoDocs/Acronyms.yml
Labels: category/styleguide

#4459 Readability improvements, update Content Templates and Infinite Editing
  Fundamentals/Backoffice/Content-Templates/index.md
  Fundamentals/Backoffice/Infinite-editing/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4462 Updated details about fixed typo in the forms AllowEditableFormSubmissions configuration setting.
  Add-ons/UmbracoForms/Developer/Configuration/index.md
Labels: category/umbraco-forms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4460 Correct casing for AngularJS
  .github/styles/UmbracoDocs/Names.yml
  Add-ons/Umbraco-Deploy/Extending/index-v8.md
  Add-ons/Umbraco-Deploy/Extending/index.md
  Development-Guidelines/Coding-Standards/naming-conventions.md
  Development-Guidelines/building-angular-project.md
  Reference/Configuration-for-Umbraco-7-and-8/dashboard/index-v7.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4466 Added note for property alias casing
  Fundamentals/Data/Defining-content/index-v8.md
  Fundamentals/Data/Defining-content/index.md
  Tutorials/Creating-Basic-Site/Document-Types/index.md
Labels: category/umbraco-cms

#4469 Follow-Through from Rest API to Heartcore
  Implementation/Rest-Api/index.md
Labels: category/umbraco-heartcore, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4467 Update Fundamentals -- Login -- index.md
  Fundamentals/Backoffice/Login/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4470 Updated the organisation section on cloud with some more information
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/Organizations/images/Cloud-org-overview.png
  Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/Organizations/index.md
Labels: category/umbraco-cloud

#4468 Update Working with stylesheets and JavaScript index.md
  Fundamentals/Design/Stylesheets-Javascript/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4473 Fixed typo in empty
  Add-ons/Umbraco-Deploy/Installing-Deploy/Existing-site/index.md
Labels: category/grammar, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4472 Added docs about breaking changes between 10 and 11
  Fundamentals/Setup/Upgrading/umbraco11-breaking-changes.md
Labels: hacktoberfest-accepted, release/11.0.0, hacktoberfest/contrib-2022

#4471 Added video link...
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/index.md
Labels: category/umbraco-forms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4463 Add V8 version of Nucache settings
  Reference/Configuration-for-Umbraco-7-and-8/nucache-settings.md
  Reference/Configuration/NuCacheSettings/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4474 Updated Examine docs for V8
  Reference/Searching/Examine/Indexing/index-v8.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4479 updated the article with a new GIF and style guide changes
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/images/Cloud-trial-gif.gif
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/images/start-trial.gif
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index-v8.md
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Labels: category/umbraco-cloud, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4481 Added basic auth back to project settings
  Umbraco-Cloud/Set-Up/Project-settings/index.md
Labels: category/umbraco-cloud

#4485 Amended view components sample
  Reference/Templating/Mvc/ViewComponents.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4483 Instructions for restoring a bacpac file
  Umbraco-Cloud/Databases/Backups/index.md
Labels: category/umbraco-cloud

#4480 Improve readability of section trees
  Extending/Section-Trees/Trees/index-v8.md
  Extending/Section-Trees/Trees/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4490 Fixed the docs
  Reference/Configuration/filesystemProviders.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4491 cleaned up code, removed li tag
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4494 Fix custom error page config formatting
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4495 Remove duplicate key from Umbraco deploy configuration sample json object
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Labels: hacktoberfest-accepted, category/umbraco-deploy, hacktoberfest/contrib-2022

#4498 Update config sample
  Reference/Configuration/Serilog/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4499 Readability improvements - Fundamentals Backoffice Sections
  Fundamentals/Backoffice/Sections/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4497 Fix typos and grammar in Umbraco Forms documentation
  Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md
  Add-ons/UmbracoForms/Developer/Extending/index.md
  Add-ons/UmbracoForms/Developer/Forms-in-the-Database/index-v8.md
  Add-ons/UmbracoForms/Developer/Healthchecks/index.md
  Add-ons/UmbracoForms/Developer/Localization/index.md
  Add-ons/UmbracoForms/Developer/Security/index.md
  Add-ons/UmbracoForms/Developer/index-v7.md
  Add-ons/UmbracoForms/Developer/index.md
Labels: category/umbraco-forms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4501 Update installing-nightly-builds.md
  Fundamentals/Setup/Install/installing-nightly-builds.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4492 Block Grid release is moved to Umbraco 11
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Labels: category/umbraco-cms

#4493 Examine Searchers for v10
  Reference/Searching/Examine/examine-management-v7.md
  Reference/Searching/Examine/examine-management.md
  Reference/Searching/Examine/images/examine-management-search-field.png
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4506 [AMEND] VALE updates to Custom Errors tutorials
  Tutorials/Custom-Error-Pages/index-v8.md
  Tutorials/Custom-Error-Pages/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4509 Readability improvements - Fundamentals Backoffice Variants
  Fundamentals/Backoffice/Variants/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4500 Update wording of explanation of default Content Version Cleanup
  Fundamentals/Data/Content-Version-Cleanup/index.md
Labels: category/umbraco-cms

#4453 Update HSTS health check guide based on ASP.NET docs
  Extending/Health-Check/Guides/StrictTransportSecurityHeader.md
Labels: category/umbraco-cms, dteam/review

#4510 Update ImagingSettings
  Reference/Configuration/ImagingSettings/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4515 Making Google Authentication Tutorial Friendlier
  Tutorials/Add-Google-Authentication/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4517 Added some bold to the fields
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Conditional-Logic/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4444 Add TokenEndPoint and AuthorizationEndpoint explanation
  Reference/Security/Authenticate-with-Active-Directory/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4281 Docs updates for Umbraco Forms 10.2.
  Add-ons/UmbracoForms/Developer/AjaxForms/index.md
  Add-ons/UmbracoForms/Developer/BlockListFilters/index.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Developer/Configuration/type-details.md
  Add-ons/UmbracoForms/Developer/ContentApps/index.md
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Magic-String-Format-Function.md
  Add-ons/UmbracoForms/Developer/Extending/index.md
  Add-ons/UmbracoForms/Developer/IFileSystem/index.md
  Add-ons/UmbracoForms/Developer/IPreValueTextFileStorage/index.md
  Add-ons/UmbracoForms/Developer/Magic-Strings/index-v7.md
  Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
  Add-ons/UmbracoForms/Developer/index.md
Labels: category/umbraco-forms, category/pending-release

#4478 Configuring Azure Key Vault via Azure Web App
  Extending/Key-Vault/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4521 Make Zapier Tutorial more friendly
  Tutorials/Connecting-Umbraco-Forms-and-Zapier/index.md
Labels: category/styleguide

#4518 Updating User Groups note on starting nodes.
  Fundamentals/Data/Users/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4519 V11: Update LogViewer docs
  Fundamentals/Backoffice/LogViewer/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, release/11.0.0, hacktoberfest/contrib-2022

#4523 Add EnableDefaultCharReplacements to settings
  Reference/Configuration/RequestHandlerSettings/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, release/11.0.0, hacktoberfest/contrib-2022

#4524 V11: Update Custom Package Migration examples
  Extending/Packages/Creating-a-Package/index-v11.md
Labels: category/umbraco-cms, hacktoberfest-accepted, release/11.0.0, hacktoberfest/contrib-2022

#4528 Improve readability --> Fundamentals Setup Install
  Fundamentals/Setup/Install/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4531 Fixed vale on the ImageCropper article
  .github/styles/UmbracoDocs/Acronyms.yml
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
Labels: category/umbraco-cms, release/11.0.0

#4532 Applies Readability Improvements to the Contribute folder
  Contribute/Adding-Metadata/index.md
  Contribute/Code-samples/index.md
  Contribute/DocsTemplates/TutorialsTemplates.md
  Contribute/File-Naming-Conventions/index.md
  Contribute/How-to-add-a-new-version/index.md
  Contribute/Issues/index.md
  Contribute/Markdown-Conventions/index.md
  Contribute/Pull-Requests/index.md
  Contribute/Style-Guide/index.md
  Contribute/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4526 Update Create a Custom Dashboard
  Tutorials/Creating-a-Custom-Dashboard/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4533 Update IContentFinder.md
  Reference/Routing/Request-Pipeline/IContentFinder.md
Labels: category/umbraco-cms

#4516 Added some bold, as well as changed some sentences
  Add-ons/UmbracoForms/Editor/Creating-a-Form/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4476 Provide details about block editor label syntax
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index-v8.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/label-property-configuration.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v7.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v8.md
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Labels: category/umbraco-cms, dteam/review

#4487 Add sending allowed children notification article
  Reference/Notifications/SendingAllowedChildrenNotification/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4535 Test: Update vale rule for HTML
  .github/styles/UmbracoDocs/Names.yml
  Add-ons/UmbracoForms/Developer/Working-With-Data/index-v8.md
  Extending/Content-Apps/index.md
  Tutorials/Creating-a-Custom-Dashboard/index.md
Labels: category/styleguide

#4502 Added Video Link
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index.md
Labels: category/umbraco-forms

#4539 Upgrade notes for Forms/Deploy 11
  Add-ons/Umbraco-Deploy/Extending/index.md
  Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
  Add-ons/UmbracoForms/Installation/Version-Specific.md
Labels: category/umbraco-forms, hacktoberfest-accepted, category/umbraco-deploy, release/11.0.0, hacktoberfest/contrib-2022

#4542 Readability Improvements base on style guide
  Development-Guidelines/Coding-Standards/index.md
  Development-Guidelines/Coding-Standards/jquery-guidelines.md
  Development-Guidelines/Coding-Standards/js-guidelines.md
  Development-Guidelines/Coding-Standards/naming-conventions.md
  Development-Guidelines/building-angular-project.md
  Development-Guidelines/index.md
  Getting-Started/Developing-websites-with-Umbraco/Customizing-Umbraco-sites/index.md
  Getting-Started/Developing-websites-with-Umbraco/Extending-the-Umbraco-Backoffice/index.md
  Getting-Started/Developing-websites-with-Umbraco/index.md
  Getting-Started/Editing-websites-with-Umbraco/index.md
  Getting-Started/Where-can-I-get-help/index.md
  Getting-Started/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022

#4537 Update and rename/move static asset cache tutorial to "Reference/Response Caching"
  Reference/Response-Caching/index.md
  Reference/index.md
  Tutorials/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, hacktoberfest/contrib-2022

#4534 Added SendingChildrenNotification to list of editormodel notifications
  Reference/Notifications/EditorModel-Notifications/index.md
Labels: category/umbraco-cms, hacktoberfest-accepted, dteam/review

#4520 Added a note based on a question.
  Add-ons/The-Licensing-model/index.md
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2022

#4544 Updated "Default Data Types" article in relation to the RTE
  Fundamentals/Data/Data-Types/default-data-types.md
Labels: category/umbraco-cms, release/11.0.0

#4548 Update to Umbraco 11 breaking changes documentation
  Fundamentals/Setup/Upgrading/umbraco11-breaking-changes.md
Labels: category/styleguide

#4551 Improve readability --> Fundamentals Data Adding-Tabs
  Fundamentals/Data/Adding-Tabs/index.md
Labels: hacktoberfest-accepted, category/styleguide, hacktoberfest/contrib-2022
