Repository umbraco/UmbracoDocs, pull requests merged in 2022-05, with the labels that each got.

#3947 Update Adding-a-Fieldtype.md
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
Labels: category/umbraco-forms

#3948 Added Content Comparision & Transfer Now sections
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/images/Compare_option.png
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/images/Comparing_Content.png
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/images/Transfer_Content.png
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/images/Transfernow_option.png
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/index.md
  Tutorials/Editors-Manual/Getting-Started-With-Umbraco/index.md
Labels: category/umbraco-cloud

#3953 Added docs for v9 to v10 upgrade
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms

#3957 Updates property name to match appsettings-schema
  Reference/V9-Config/SecuritySettings/index.md
Labels: category/umbraco-cms

#3955 Update index.md
  Reference/V9-Config/RichTextEditorSettings/index.md
Labels: category/umbraco-cms

#3959 Typo fix and commas
  Reference/Security/password-reset.md
Labels: category/grammar

#3962 Update IContentFinder.md
  Reference/Routing/Request-Pipeline/IContentFinder.md
Labels: category/umbraco-cms

#3960 Conditions for Date field
  Add-ons/UmbracoForms/Developer/Prepping-Frontend/index-v7.md
  Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Conditional-Logic/index.md
Labels: category/umbraco-forms

#3958 Update reserved keywords in umbraco
  Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
Labels: category/umbraco-heartcore

#3933 Add UmbracoApplicationLifetime notifications
  Reference/Notifications/UmbracoApplicationLifetime-Notifications/index.md
Labels: category/umbraco-cms

#3966 SmidgeHelper ignores Umbraco:CMS:Hosting:Debug
  Fundamentals/Design/Stylesheets-Javascript/index.md
Labels: category/umbraco-cms

#3970 Added a section about blob storage
  Umbraco-Cloud/Frequently-Asked-Questions/index.md
Labels: category/umbraco-cloud

#3967 V9 to v10 upgrade patch
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms

#3949 Umbraco 10 rc breaking changes docs
  Fundamentals/Setup/Upgrading/umbraco10-breaking-changes.md
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms

#3972 Added a note in an attempt to avoid confusion
  Reference/Querying/MemberShipHelper/index.md
Labels: category/umbraco-cms

#3973 guide on how to sign on the first time after UmbracoID migration for heartcore projects.
  Umbraco-Heartcore/images/Login1.png
  Umbraco-Heartcore/images/ssoHC1.png
  Umbraco-Heartcore/images/ssoHC2.png
  Umbraco-Heartcore/images/ssoHC4.png
  Umbraco-Heartcore/images/ssoHC6.png
  Umbraco-Heartcore/sso-guide.md
Labels: category/umbraco-heartcore

#3977 Fixed Typo
  Tutorials/Editors-Manual/Version-Management/index-v7.md
  Tutorials/Editors-Manual/Version-Management/index.md
Labels: category/umbraco-cms

#3978 Removed Uno reference
  Getting-Started/Developing-websites-with-Umbraco/index.md
Labels: category/umbraco-cms

#3979 V10: Update the upgrade page to show how to re-enable appsettings intellisense in v10
  Fundamentals/Setup/Upgrading/version-specific.md
Labels: category/umbraco-cms

#3980 Documentation for the CDN Caching and Optimization subpage - Umbraco …
  Umbraco-Cloud/Set-Up/Manage-CDN-Caching/images/caching-subpage.png
  Umbraco-Cloud/Set-Up/Manage-CDN-Caching/images/purge-cache.png
  Umbraco-Cloud/Set-Up/Manage-CDN-Caching/index.md
Labels: category/umbraco-cloud

#3981 Update index.md
  Umbraco-Cloud/Set-Up/Manage-CDN-Caching/index.md
Labels: category/umbraco-cloud

#3983 Added Umbraco Cloud as hosting infra tip
  Fundamentals/Setup/Requirements/index-v7.md
  Fundamentals/Setup/Requirements/index-v8.md
  Fundamentals/Setup/Requirements/index.md
Labels: category/umbraco-cms

#3982 Documented breaking changes for Forms and Deploy 10.
  Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
  Add-ons/Umbraco-Deploy/Upgrades/index-v9.md
  Add-ons/Umbraco-Deploy/Upgrades/index.md
  Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
  Add-ons/UmbracoForms/Developer/Themes/index.md
  Add-ons/UmbracoForms/Installation/Version-Specific.md
  Add-ons/UmbracoForms/Installation/index.md
Labels: category/umbraco-forms, category/pending-release, category/umbraco-deploy

#3984 Updates to release notes section with release notes fro 2022-05-23 release
  Umbraco-Cloud/Release-Notes/2022-05-23-ReleaseNotes.md
  Umbraco-Cloud/Release-Notes/images/CDCachingAndOptimization.gif
  Umbraco-Cloud/Release-Notes/images/Members.png
  Umbraco-Cloud/Release-Notes/images/PendingOrgInvite.png
  Umbraco-Cloud/Release-Notes/images/Top50MediaFiles.gif
  Umbraco-Cloud/Release-Notes/index.md
Labels: category/umbraco-cloud

#3996 Added versionTo tag
  Extending/Property-Editors/Property-Actions/index.md
Labels: category/umbraco-cms

#3993 Verified Property Editor Tutorial for v10
  Tutorials/Creating-a-Property-Editor/index.md
  Tutorials/Creating-a-Property-Editor/part-2.md
  Tutorials/Creating-a-Property-Editor/part-3.md
Labels: category/umbraco-cms, category/umbraco-v10

#3992 Added versionTo tag and "sections" in Root Elements section
  Extending/Property-Editors/package-manifest.md
Labels: category/umbraco-cms

#3991 Updated images for v10
  Fundamentals/Backoffice/Variants/images/allow-variance_v10.png
  Fundamentals/Backoffice/Variants/images/languages_v10.png
  Fundamentals/Backoffice/Variants/images/varying-content_v10.png
  Fundamentals/Backoffice/Variants/images/varying-properties_v10.png
  Fundamentals/Backoffice/Variants/index.md
Labels: category/umbraco-cms

#3999 Move authenticate with AD to a folder
  Reference/Security/Authenticate-with-Active-Directory/Authenticate-With-AD-vpre8.md
  Reference/Security/Authenticate-with-Active-Directory/authenticate-with-AD-v800.md
  Reference/Security/Authenticate-with-Active-Directory/authenticate-with-AD.md
  Reference/Security/index-v7.md
  Reference/Security/index-v8.md
  Reference/Security/index-vpost-7.5.0.md
Labels: category/umbraco-cms

#3990 Make it a little clearer that this article is not yet relevant.
  Extending/UI Library/index.md
Labels: category/umbraco-cms

#3989 Update version on deploy ci/cd doc
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
Labels: category/umbraco-deploy

#4004 Verifying Sections article for v10
  Extending/Section-Trees/sections.md
Labels: category/umbraco-cms, category/umbraco-v10

#4008 Update system requirements for 10.x
  Fundamentals/Setup/Requirements/index-v10.md
Labels: category/umbraco-cms, category/umbraco-v10

#4010 Update untattended-install documentation for 10.x
  Fundamentals/Setup/Install/Unattended-Install-v10.md
Labels: category/umbraco-cms, category/umbraco-v10

#4012 Added AzureDevOps example for Umbraco 9.
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
  Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/index-v8.md
Labels: category/umbraco-deploy

#4018 Added Umbraco 10 specific code example for article
  Tutorials/Add-Google-Authentication/index.md
Labels: category/umbraco-cms, category/umbraco-v10

#4016 V10: Healthcheck documentation.
  Extending/Health-Check/Guides/ClickJackingProtection.md
  Extending/Health-Check/Guides/ContentSniffingProtection.md
  Extending/Health-Check/Guides/CrossSiteScriptingProtection.md
  Extending/Health-Check/Guides/DebugCompilationMode.md
  Extending/Health-Check/Guides/ExcessiveHeaders.md
  Extending/Health-Check/Guides/FixedApplicationUrl.md
  Extending/Health-Check/Guides/FolderAndFilePermissions.md
  Extending/Health-Check/Guides/HttpsConfiguration.md
  Extending/Health-Check/Guides/MacroErrors.md
  Extending/Health-Check/Guides/NotificationEmail.md
  Extending/Health-Check/Guides/SMTP.md
  Extending/Health-Check/Guides/StrictTransportSecurityHeader.md
  Extending/Health-Check/Guides/index.md
  Extending/Health-Check/index.md
Labels: category/umbraco-v10
