Repository umbraco/UmbracoDocs, pull requests merged in 2022-04, with the labels that each got.

#3889 Added reference to Services and Helpers
  Reference/Scheduling/index-v8.md
Labels: category/umbraco-cms

#3890 Create folders for notifications
  Reference/Events/ContentService-Events.md
  Reference/Events/ContentTypeService-Events.md
  Reference/Events/DataTypeService-Events.md
  Reference/Events/FileService-Events.md
  Reference/Events/LocalizationService-Events.md
  Reference/Events/MediaService-Events.md
  Reference/Notifications/ContentService-Notifications/index.md
  Reference/Notifications/ContentTypeService-Notifications/index.md
  Reference/Notifications/Creating-And-Publishing-Notifications/index.md
  Reference/Notifications/DataTypeService-Notifications/index.md
  Reference/Notifications/FileService-Notifications/index.md
  Reference/Notifications/LocalizationService-Notifications/index.md
  Reference/Notifications/MediaService-Notifications/index.md
  Reference/Notifications/MediaTypeService-Notifications/index.md
  Reference/Notifications/MemberTypeService-Notifications/index.md
  Reference/Notifications/index.md
  Reference/Scheduling/index.md
Labels: category/umbraco-cms

#3854 Update index.md
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms

#3895 Adds another e-mail service
  Umbraco-Cloud/Set-Up/SMTP-settings/index.md
Labels: category/umbraco-cloud

#3893 Mention InstallMissingDatabase setting on Unattended-Install page
  Fundamentals/Setup/Install/Unattended-Install.md
Labels: category/umbraco-cms

#3896 Config rewrites patch
  Umbraco-Cloud/Getting-Started/Baselines/Configuration-files/index.md
  Umbraco-Cloud/Set-Up/Config-Transforms/images/appSettings.png
  Umbraco-Cloud/Set-Up/Config-Transforms/index-v7.md
  Umbraco-Cloud/Set-Up/Config-Transforms/index.md
Labels: category/umbraco-cloud, category/umbraco-v9

#3898 Update external services with port 25 specifics
  Umbraco-Cloud/Set-Up/External-Services/index.md
Labels: category/umbraco-cloud

#3861 Add Azure Key Vault Article
  Extending/Key-Vault/index.md
Labels: category/umbraco-cms, community/review

#3901 Added default snippets and their definition
  Fundamentals/Design/Partial-View-Macro-Files/index.md
  Fundamentals/Design/Partial-Views/index.md
Labels: category/umbraco-cms

#3903 Update index.md
  Extending/Key-Vault/index.md
Labels: category/umbraco-cms

#3906 Make it clear where in the appSettings the Forms settings go
  Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha2/index.md
Labels: category/umbraco-forms

#3858 Docs updates for upcoming 8.12.0/9.4.0 release of Umbraco Forms.
  Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
  Add-ons/UmbracoForms/Developer/Configuration/index.md
  Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
  Add-ons/UmbracoForms/Developer/Security/index.md
Labels: category/umbraco-forms, category/pending-release

#3859 Docs updates for upcoming 4.6.0/9.4.0 release of Umbraco Deploy.
  Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
  Add-ons/Umbraco-Deploy/Extending/index-v8.md
  Add-ons/Umbraco-Deploy/Extending/index.md
Labels: category/pending-release, category/umbraco-deploy

#3908 Migrate existing site v9 patch
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/images/deployDashBoard.png
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index-v8.md
  Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Labels: category/umbraco-cloud, category/umbraco-v9

#3915 Fixed broken link and minor grammar
  Reference/Notifications/ContentService-Notifications/index.md
Labels: category/umbraco-cms

#3919 Typo fix
  Fundamentals/Setup/Server-Setup/iis/index.md
Labels: category/umbraco-cms

#3917 Added contentVersionCleanupPolicyGlobalSettings and fixed typos, grammar, and lint issues
  Fundamentals/Code/Subscribing-To-Events/index.md
  Reference/Config/umbracoSettings/index.md
  Reference/V9-Config/umbracoSettings/index.md
Labels: category/grammar, category/umbraco-cms

#3921 Removed tip as links are already removed
  index.md
Labels: category/umbraco-cms

#3920 Added umbraco.config/NuCache info
  Reference/Config/index.md
Labels: category/umbraco-cms

#3923 Umbraco 9 - Using case updated to correct model
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
Labels: category/umbraco-cms

#3928 Added missing detail about TempData value for the Id of the record created after a form submission.
  Add-ons/UmbracoForms/Editor/Attaching-Workflows/index.md
Labels: category/umbraco-forms

#3927 Note about Cloud
  Reference/V9-Config/MaximumUploadSizeSettings/index.md
Labels: category/umbraco-cms

#3926 Update index.md for Creating-A-Property-Editor
  Tutorials/Creating-a-Property-Editor/index.md
Labels: category/umbraco-cms

#3929 Link to V8 Forms nuget
  Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
Labels: category/umbraco-forms

#3932 Typo Customize -> Custoimize
  Add-ons/UmbracoForms/Developer/index.md
Labels: category/umbraco-forms

#3930 Added details on working with single records from form submissions.
  Add-ons/UmbracoForms/Developer/Working-With-Data/index-v8.md
Labels: category/umbraco-forms

#3866 Added details on the configuration options available for install of Umbraco default data.
  Reference/V9-Config/InstallDefaultDataSettings/index.md
  Reference/V9-Config/index.md
Labels: category/pending-release, category/umbraco-cms

#3899 Add documentation about serverside request handling options
  Implementation/Services/index.md
Labels: category/pending-release, category/umbraco-cms

#3931 Added documentation about configuring 2fa for users on 9.5+
  Reference/Security/Two-factor-authentication/images/configure-2fa.png
  Reference/Security/Two-factor-authentication/images/disable-2fa.png
  Reference/Security/Two-factor-authentication/images/enable-2fa.png
  Reference/Security/Two-factor-authentication/images/login-2fa.png
  Reference/Security/Two-factor-authentication/images/user-panel.png
  Reference/Security/Two-factor-authentication/images/verify-disable.png
  Reference/Security/Two-factor-authentication/index-v9.3.0.md
  Reference/Security/Two-factor-authentication/index.md
Labels: category/pending-release, category/umbraco-cms

#3935 Added Handling errors in ASP.NET Core section
  Tutorials/Custom-Error-Pages/index.md
Labels: category/umbraco-cms

#3936 New page set-up/Application settings
  Umbraco-Cloud/Set-Up/Application-Settings/Images/EnableClientCertificateLoadedFromFileSystem.gif
  Umbraco-Cloud/Set-Up/Application-Settings/Images/test
  Umbraco-Cloud/Set-Up/Application-Settings/index.md
Labels: category/umbraco-cloud

#3939 Eye Dropper Color Picker value type in v9
  Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Eye-Dropper-Color-Picker/index.md
Labels: category/umbraco-cms

#3942 Deploy settings patch
  Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
  Umbraco-Cloud/Deployment/Deploy-Settings/index-v7.md
  Umbraco-Cloud/Deployment/Deploy-Settings/index.md
  Umbraco-Cloud/Deployment/index.md
Labels: category/umbraco-deploy

#3940 Cloud Release notes for 25-04-2022 release
  Umbraco-Cloud/Release-Notes/2022-04-25-ReleaseNotes.md
  Umbraco-Cloud/Release-Notes/images/EnableClientCertificateLoadedFromFileSystem.gif
  Umbraco-Cloud/Release-Notes/index.md
Labels: category/umbraco-cloud

#3944 Fix syntax highlighting in Localization samples
  Extending/Language-Files/index.md
Labels: category/umbraco-cms
